### ISSUE TITLE
Request for portable version

### ISSUE THREAD

**Issue by JeanPaulLucien** [Eclipse-Community/r3dfox-old#10]
Hi. Could you create a version to use without installation? Place profile folder in browser folder.

**Comment by the-r3dacted** [comment]
I'm not really sure how to do this. If you can tell me how, I can add a portable mode function next release.

**Comment by jonm58** [comment]
https://github.com/runningcheese/RunningCheese-Firefox
lol

**Comment by GunGunGun** [comment]
> Hi. Could you create a version to use without installation? Place profile folder in browser folder.

Portable Firefox is pretty easy to make, just run `firefox -p portable` and everything will be grouped inside portable folder, just that.

**Comment by adeii** [comment]
If you don't mind, I'd made r3dfox 122 portable x64. Works great on Win 7.
https://github.com/adeii/supermium-portable/releases/download/F121/r3dfox-portable-win64-122.0.1-22.7z

**Comment by GunGunGun** [comment]
> If you don't mind, I'd made r3dfox 122 portable x64. Works great on Win 7. https://github.com/adeii/supermium-portable/releases/download/F121/r3dfox-portable-win64-122.0.1-22.7z

This is great, thanks.
Windows 7 needs all the helps considering it's getting forgotten due to recent events, it would've gotten a Extended Core like Vista at this point to make it be able to run Windows 10, 11 applications.

**Comment by the-r3dacted** [comment]
@adeii Is this a custom compile or did you make it by extracting the installer?

**Comment by adeii** [comment]
@K4sum1 Made by extracting installer (and icons) from your release. It is mod of project for Firefox portable by PortApps.io.

**Comment by adeii** [comment]
New 32bit portable version:
https://github.com/adeii/supermium-portable/releases/download/F1235/R3dfox-portable-win32-124.0-24.7z

**Comment by the-r3dacted** [comment]
There's a reason why I haven't made a 124 release.
![ScreenShot_20240320114828](https://github.com/Eclipse-Community/r3dfox/assets/77039240/227d3cdd-e794-4802-ae8b-d3dcc3e6e50b)

I need to get around to fixing this, but I just haven't been feeling it.

**Comment by adeii** [comment]
> There's a reason why I haven't made a 124 release.

I confirm that this x86 build force closes on Win7 x64 after 1 minute, but no problem on Win8. 
Also fails with VxKex 1.1 + api-ms-win-shcore-scaling-l1-1-1.dll.

**Comment by JhonnyBeige** [comment]
you can make the cleanest portable with 
https://github.com/adonais/libportable
https://sourceforge.net/projects/libportable/files/Tools/portable_bin.7z/

also firefox by default makes a lot of connections on start up,  you should look up these projects for optimizations 
https://wiki.archlinux.org/title/Firefox/Privacy
https://codeberg.org/chippy/icecat-for-windows
https://github.com/adonais/iceweasel

**Comment by the-r3dacted** [comment]
@adeii Can you remove any extra extensions from your portable versions? I was trying to figure out why "AdBlocker for YouTube" kept being automatically installed for a user until I discovered it's part of your portable mod.

**Comment by adeii** [comment]
@K4sum1 Not a problem at all. I'll also update 124.0.3 to latest, with hotfix.
I don't know which build got additional plugin, but it is in distribution/extensions/jid1-q4sG8pYhq8KGHs@jetpack.xpi.
Just delete it.

**Comment by the-r3dacted** [comment]
> @K4sum1 Not a problem at all. I'll also update 124.0.3 to latest, with hotfix. I don't know which build got additional plugin, but it is in distribution/extensions/[jid1-q4sG8pYhq8KGHs@jetpack.xpi](mailto:jid1-q4sG8pYhq8KGHs@jetpack.xpi). Just delete it.

I just saw this after making https://github.com/Eclipse-Community/r3dfox/issues/48

If 124.0.3 doesn't have this, I'll lighten the language

**Comment by adeii** [comment]
No added Adblock in r3dfox builds, just in firefox ones.

**Comment by the-r3dacted** [comment]
@adeii A friend really wants 124.0.3 Librewolf builds, could you make them?

**Comment by adeii** [comment]
> @adeii A friend really wants 124.0.3 Librewolf builds, could you make them?

Not a problem, but latest Librewolf is 124.0.1. It uses native portable exe in build.
You can get
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-portable-win32-124.0.1.7z
and
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-portable-win64-124.0.1-1.7z

Nothing too much to make:
-Downgrade Major Subsystem Version from 000A to 0006 for main two EXEs (librewolf and private_browsing)
-Add api-ms-win-shcore-scaling-l1-1-1.dll
-Replace lgpllibs.dll and xul.dll from your latest r3dfox
-Hex edit xul.dll from 124.0.3 to 124.0.1
-Edit browser/omni.ja/default/preferences/firefox.js for browser.taskbar.lists.legacyBackend from false to true.

**Comment by the-r3dacted** [comment]
They mostly want it for the hotfix, which apparently affects more than just 11. Only the latest release has it.

**Comment by the-r3dacted** [comment]
125 has Mypal68 style portable mode. Extract the installer, rename core folder to whatever and move it wherever. Create a blank file named pmprt.mod in r3dfox\browser folder, and run.

To migrate over your old profile, just replace the profile in the profile folder under the r3dfox folder, both roaming and local.

https://github.com/Eclipse-Community/r3dfox/releases/tag/125.0rc

**Comment by i486** [comment]
In regards to full portability: How can I run different versions of r3dfox side by side?

My main browser is version 125.0.2 with pmprt.mod installed. I've also downloaded the portable version, r3dfox 125.0.3.

Now, I want to test them by running them together. Version 125.0.2 is already running with my profile. But when I try to open portable r3dfox 125.0.3, it just opens a new window of my 125.0.2 version. I've already tried changing the executable name of the 125.0.3 portable version, but it didn't work.

**Comment by the-r3dacted** [comment]
You can't, it would need a different internal name to open alongside normal r3dfox which would require rebuilding and I can't be bothered to do that. The portability means that it just stores the profile in the browser folder instead of appdata.

**Comment by GunGunGun** [comment]
> In regards to full portability: How can I run different versions of r3dfox side by side?
> 
> My main browser is version 125.0.2 with pmprt.mod installed. I've also downloaded the portable version, r3dfox 125.0.3.
> 
> Now, I want to test them by running them together. Version 125.0.2 is already running with my profile. But when I try to open portable r3dfox 125.0.3, it just opens a new window of my 125.0.2 version. I've already tried changing the executable name of the 125.0.3 portable version, but it didn't work.

Add -no-remote to your shortcut

**Comment by Rusenche** [comment]
Hi @K4sum1 and @adeii

I am an **Ungoogled chromium** user.

I came across your portable versions.

I have been experimentally testing for a month (with a lot of searching for add-ons/extensions for Firefox, because the ones I have on Chromium are not available for Firefox. It's a shame that users don't share the names of the extensions they use.) **Plasmafox v.133.0e x64 portable** - https://github.com/Eclipse-Community/r3dfox/releases/tag/v133.0e

So far I like it and I'm happy with it.

@K4sum1, today you uploaded **ESR v128.6.0 for Vista+** - https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.6.0/ and I decided to test r3dfox_esr-128.6.0.en-US.win64.portable.

From the **Plasmafox v.133.0e x64 portable** version I archived the entire _Profile_ folder and unzipped it to the _Profile_ folder of **r3dfox_esr-128.6.0.en-US.win64.portable** (inside this folder).

It turned out that the profile is both there and this **ESR** version cannot be started because the saved portable profile is in conflict.

![version](https://github.com/user-attachments/assets/b35bfc02-de2f-4c5c-897e-dd8f6ac66237)

This means that the profile is both portable and not portable. If, for example, we use a version that is different from the **ESR** version (because, for example, it is a higher version, and the **ESR** version is a lower version), then the migration for the purpose of experimentation (when transferring all favorite settings from the _Profile_ folder) - the **ESR** version cannot be started in any case when transferring settings (**Profile** folder) from a higher version (a version that is not ESR).

I hope you understand what I mean. And I'm looking for an easy solution. All this is for the purpose of experimentation, because the transition from **Ungoogled chromium** (the destruction of this browser is intentional due to the edifying and greedy forced imposition of **MV3** and this is what the **_aggressor Google_** is doing) will at some point require migration to the variety of Firefox variants and I only use portable versions.

**Comment by the-r3dacted** [comment]
Delete compatibility.ini in the Profile folder

**Comment by Rusenche** [comment]
> [K4sum1](https://github.com/K4sum1) commented [1 hour ago](https://github.com/Eclipse-Community/r3dfox/issues/10#issuecomment-2571593830)
> Delete compatibility.ini in the Profile folder

@K4sum1, thanks for the answer. This is very useful, I'll write it down.

@K4sum1, for some reason there is some discrepancy or... contraction in **r3dfox_esr-128.6.0.en-US.win64.portable**.

This is how it looks in **Plasmafox v.133.0e x64 portable**:

![Plasmafox v 133 0e x64 portable](https://github.com/user-attachments/assets/306b2c74-3635-452e-a1f9-a17cd00ece85)

This is how it looks in **r3dfox_esr-128.6.0.en-US.win64.portable**:

![r3dfox_esr-128 6 0 en-US win64 portable](https://github.com/user-attachments/assets/a07fb4be-f478-4cc5-921d-83acf14024d4)

When I go to the top right to the triangle (where it shows the number **2**) and try to press it - just millimeters above it, the browser closing is activated and several times I accidentally closed the browser, that's not what I wanted to press.

In both browsers in the pictures _**Use r3dfox theme styles**_ is enabled, but only in the **ESR** version are the two menus (open tabs and for closing the browser) so close together and overlap.

**Comment by the-r3dacted** [comment]
128 and 133 have pretty different theme code. Maybe I could backport the new code from 133 to 128, but would be a lot of effort for not much gain.
