### ISSUE TITLE
[Youtube] Video player area turned green

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#109]
Windows 8.1 64 bit. r3dfox Beta b128.0 64 bit portable. F5 or Ctrl + F5 doesn't help. The only way to get rid of it is to close this tab and reopen the Youtube link in a new tab. Triggered when I'm leaving the tab playing Youtube to browse in a new tab. When I came back, the video player area turned green. Note: The audio is still being played.

**Comment by the-r3dacted** [comment]
Hmm, maybe I should try downgrading to 127 to test videos. I've noticed some weirdness and I assumed it was just YouTube being a shit like usual.

**Comment by the-r3dacted** [comment]
I decided why not now. I downgraded to 127 and YouTube is still fucked. This is probably an issue on their end trying to fuck with adblocker users.

**Comment by the-r3dacted** [comment]
I will say I don't have this issue specifically, but I am also running 8.1, and it is probably par for the course with how fucked YouTube has gotten recently.

**Comment by ghost** [comment]
It seems the bug is triggered randomly. I don't have a way to effectively reproduce it.

**Comment by the-r3dacted** [comment]
I can tell you that I use r3dfox basically exclusively on YouTube and I haven't seen this once.

**Comment by the-r3dacted** [comment]
Oh, can you test stock Firefox 128? It still works on 8.1 if you subsystem mod it.

**Comment by ghost** [comment]
I don't want to use stock Firefox. Btw, I can't reproduce it on r3dfox anymore. It triggered just once and not yet triggered again.

**Comment by the-r3dacted** [comment]
Hmm, probably just YouTube being funny then if it's a one time thing. The suggestion was to see if it could be replicated in stock Firefox to see if it was upstream or r3dfox issue.
