### ISSUE TITLE
Just summary about Firefox

### ISSUE THREAD

**Issue by JeanPaulLucien** [Eclipse-Community/r3dfox-old#11]
Firefox 100+ is really bad than Firefox 2-42. 2-42 version were the best. After 45 Firefox has started to collect issues, high requierments to computing power and dropping of features, adding strange features.
There are developers who does steps to bring back or save features of 2-42 version and avoid 100+ issues.

**Comment by the-r3dacted** [comment]
Fork Arctic Fox or roytam1's 45 ESR fork then
