### ISSUE TITLE
The v128 beta has fixed an issue that I've debated reporting

### ISSUE THREAD

**Issue by OpposedScroll75** [Eclipse-Community/r3dfox-old#110]
On my Windows 7 VM, versions prior to the v128 beta would not want to open the home page, showing a transparent aero window instead. Sometimes, right clicking on the program and opening a website in a new tab would jump start the program (the program would display properly).

The v128 beta has fixed this. 

The reason I was debating to report this issue is that I thought it may be a configuration issue or my GPU sucking at 3D Emulation.

Just wanted to let you know this.

**Comment by the-r3dacted** [comment]
If you're using VirtualBox, that's an issue with their software. I removed the code to disable hardware acceleration in VMs and I noticed that VirtualBox was a bit funny. I just left it as is in hopes another virtual GPU or an update would fix it. However a friend had the issue and they kept bothering me to fix it, so I added the blocklist back only for VirtualBox.
