### ISSUE TITLE
r3dfox v128 crashing upon launch for unknown reason.

### ISSUE THREAD

**Issue by TainaShiro** [Eclipse-Community/r3dfox-old#111]
![Clipboard_07-09-2024_01](https://github.com/Eclipse-Community/r3dfox/assets/115933380/4e51c6fb-ccf7-421a-88a8-72901c81a8cf)
The crash happens with both installer and portable version (64-bit). Had to revert back to v127.0.2 for the time being. Hope you'll look into it!

**Comment by the-r3dacted** [comment]
Fixed with https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0-hotfix
