### ISSUE TITLE
AVX2 Only version v128

### ISSUE THREAD

**Issue by vadimlitvinenko87** [Eclipse-Community/r3dfox-old#112]
This is not adecvate build for windows7 users, because we use W7 with maximum AVX cpu. With AVX2 no interest to sit on old software. This is shocking that new 128 build require AVX2.

**Comment by the-r3dacted** [comment]
The 128.0-hotfix build is not AVX2. The previous build I accidentally ended up making AVX2 only, and that's what that bit of text states. 128.0-hotfix has the usual SSE2 compatibility.
