### ISSUE TITLE
Last 128 build crash

### ISSUE THREAD

**Issue by vadimlitvinenko87** [Eclipse-Community/r3dfox-old#113]
Build has error when opening browser on windows 7.
[Release v128.0-hotfix](https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0-hotfix) Works fine.

**Comment by the-r3dacted** [comment]
Does 128.0-hotfix have the same crash?

**Comment by vadimlitvinenko87** [comment]
![SCRN-20240709182138](https://github.com/Eclipse-Community/r3dfox/assets/34354361/16f5a6f5-ab9f-487e-9da4-73d4c1c3052a)

> Does 128.0-hotfix have the same crash?

Yes works, i didnt seen whys issue was closed, now understood and reopen as error issue.

**Comment by the-r3dacted** [comment]
Ok, if 128.0-hotfix works, then the issue is resolved and I'm going to close this.

**Comment by vadimlitvinenko87** [comment]
Ough my bad, fix was later then release

**Comment by vadimlitvinenko87** [comment]
Sorry for misunderstood.
