### ISSUE TITLE
Whatsapp Web, Discord voice Channel etc... not working with version 128.0

### ISSUE THREAD

**Issue by MrDick004** [Eclipse-Community/r3dfox-old#114]
I just updated to version 128.0, but apparently whatsappp web doesn't seem to work anymore, on the discord site instead I can't talk in voice channels anymore, it says I have to update the browser, for the moment I'm back to version 127.0.2, I hope it will be fixed soon ;)
![aggiorna firefox](https://github.com/Eclipse-Community/r3dfox/assets/87878460/33245ab2-103b-4765-aaee-81c13ce7d9b8)

**Comment by vadimlitvinenko87** [comment]
Confirm

**Comment by the-r3dacted** [comment]
For now use a user agent switcher to use a stock Firefox user agent, at least until I fix https://github.com/Eclipse-Community/r3dfox/issues/67 and can change the useragent per site.

I didn't expect so many websites to have issues.

**Comment by MrDick004** [comment]
For those who may need it for the moment I solved it this way for version 128.0
Go to about:config
right click > new > String
Call it general.useragent.override
Evaluate Mozilla/5.0 (Windows NT 6.1; rv:109.0) Gecko/20100101 Firefox/114.0
Save, restart the browser just in case
Now the sites all work correctly

**Comment by the-r3dacted** [comment]
Going to be fixed in next release. If there are any other problem sites, please let me know.

![ScreenShot_20240712081907](https://github.com/user-attachments/assets/7b859449-f41d-474f-901c-3961b5965ef9)

**Comment by ghost** [comment]
I'm against the idea of setting per domain user agent override in about:config. Anyone experiencing problems with user agent and wanting to set per domain custom user agent can install an addon to do so. Please don't pollute about:config! Abusing about:config for stuffs like that is bad, it's even worse for the developer to set them by default!

**Comment by the-r3dacted** [comment]
Not every user is that intelligent or willing to do that. If someone sees a website not working, I'm lucky to even get an issue report. A new user will just blame the browser and use something else.

Also wait until you see Lun3r lol
