### ISSUE TITLE
Font issue non cleartype look

### ISSUE THREAD

**Issue by vadimlitvinenko87** [Eclipse-Community/r3dfox-old#115]
Standart settings after clean install is:
 In about:config
gfx.font_rendering.cleartype_params.rendering_mode = -1
gfx.font_rendering.cleartype_params.enhanced_contrast = -1 
And we have this broken font
![standart after install](https://github.com/Eclipse-Community/r3dfox/assets/34354361/43eefa5a-d5e4-482d-be80-a2339f77abf2)
After modding to
gfx.font_rendering.cleartype_params.rendering_mode = 5
gfx.font_rendering.cleartype_params.enhanced_contrast = 1 
we have better font
![moded after about_config](https://github.com/Eclipse-Community/r3dfox/assets/34354361/8a69de3a-fb13-4d68-aae3-3be7a646b17b)

**Comment by the-r3dacted** [comment]
Is this a new issue, something upstream, or just settings you think looks good?

**Comment by vadimlitvinenko87** [comment]
I intalling redfox only for testing purposes and never look different sites and dont know how old this issue. Today i see big difference in font showing in comparison with centbrowser i use as main browser.
I think it is not only "settings looks good" because native settings looks like crap sorry for my opinion.

**Comment by vadimlitvinenko87** [comment]
I don't think that my monitor so bad to show this font so poorly. My opinion native settings must be corrected as i discribed. I didnt seen options in windows 7 that can overide this, so only way to edit this in distributive. Maybe i wrong, but think not.

**Comment by vadimlitvinenko87** [comment]
As i wrote it is only my opinion and not claim as my wish only for myself. Just thought that not only i breaks my eyes on this.

**Comment by the-r3dacted** [comment]
I don't want to mess with defaults too much because it might confuse other users of the browser.
