### ISSUE TITLE
Release v128.0-hotfix crashes after installation

### ISSUE THREAD

**Issue by Komprogue** [Eclipse-Community/r3dfox-old#119]
It's still keep on crashing even in safe mode.

![r3dfox_TAzmNdytP9](https://github.com/Eclipse-Community/r3dfox/assets/84424346/fdee1982-7ebd-4bec-89e6-419b4fe0a16a)

**Comment by the-r3dacted** [comment]
Can I know more about your system? Also can you try b128? https://github.com/Eclipse-Community/r3dfox/releases/tag/b128.0

**Comment by Komprogue** [comment]
> Can I know more about your system? Also can you try b128? https://github.com/Eclipse-Community/r3dfox/releases/tag/b128.0

Windows 7 x64. 

The same issue. 

P.S. It's succesfully starting after wiping old profile, but sometimes (every second launching) get this crash again. 

![dwm_Bs4PzSp8Af](https://github.com/Eclipse-Community/r3dfox/assets/84424346/2d32311f-1c96-4902-b34b-13b98c20171e)

**Comment by the-r3dacted** [comment]
That's very weird. Can you tell me what updates you have installed, SP0 or SP1, etc?

**Comment by cartdude54** [comment]
I am now using windows 8.1 and the 128 version does not open at all

**Comment by the-r3dacted** [comment]
Actually, that might help here. 8.1 does work with stock 128 at least for me, however you need to subsystem mod it.

The easiest way is to use winvertroll.
https://board.eclipse.cx/viewtopic.php?t=652
You can just drag and drop firefox.exe onto winvertroll.exe, no need for command line. That was only the case in an older version.

Start testing 128 nightly builds from here.
https://ftp.mozilla.org/pub/firefox/nightly/2024/05/2024-05-13-21-43-35-mozilla-central/
128 nightly goes up to 2024-06-09-20-51-51. If you can give me a build where the issue first occurs, I can look into it and see if I can get a fix out.

**Comment by cartdude54** [comment]
winvertroll.exe tells me to install the 140 dll i already have installed on here thats strange lol

**Comment by the-r3dacted** [comment]
Maybe these issues are from outdated VC++ redistributables

Try this https://github.com/abbodi1406/vcredist

**Comment by cartdude54** [comment]
the winvertroll now flashes real quick when i ran it and the 128 version of the browser still did not open i also had no way to drag it to the vertroll because that must not have installed either. At least 127 works great if i have to go back to that for awhile lol

**Comment by the-r3dacted** [comment]
Normal Firefox won't install, just extract the installer with 7-zip.

**Comment by cartdude54** [comment]
no i downloaded 128 esr and extracted the files using 7 zip and it told me this app cant run on your pc

**Comment by the-r3dacted** [comment]
That's why you drag firefox.exe onto winvertroll.exe, it fixes that error.

**Comment by cartdude54** [comment]
the 128 hotfix is working for me yay

**Comment by Komprogue** [comment]
> That's very weird. Can you tell me what updates you have installed, SP0 or SP1, etc?

It has all necessary security updates installed (SP1 + kind of ESU), but redfox v128.0.3-hotfixis is still crashing (strictly at every second launch) even after wiping Eclipse Community folders from \Appdata and clean reinstalling.

**Comment by the-r3dacted** [comment]
Fixed in 129.0.2
