### ISSUE TITLE
Please adjust default per domain user agent overrides to sensible values

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#128]
Upgraded to [v128.0-2](https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0-2). I found these new user agent overrides:

general.useragent.override.discord.com -> Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

general.useragent.override.snapchat.com -> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

general.useragent.override.whatsapp.com -> Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

None of them make sense. The last version of Chromium that supports Windows 7 is 109. The last version of Firefox that supports Windows 7 is 115 ESR.

If it's your ultimate decision to bring back support for per domain user agent override in about:config then I have nothing to say anymore. But, please adjust the user agent overrides to sensible values!

For people don't need these user agent overrides, set general.useragent.site_specific_overrides to false.

Btw, if you can find a Firefox user agent that works, please use it instead of spoofing as Chrome. Thank you.

**Comment by the-r3dacted** [comment]
I used Chrome for a reason. I'm not faking Windows 10. These are needed for these websites to work.

**Comment by ghost** [comment]
> I used Chrome for a reason. I'm not faking Windows 10. These are needed for these websites to work.

Does Firefox 115 work? Btw, I'm glad that these special treatments work for these sites. With such an invalid user agent string like that, normally you will be blocked by Cloudflare already. I still think valid user agent strings will help in the long term.

**Comment by the-r3dacted** [comment]
A friend told me that they just flat out block Firefox, so I just took their word for it.

**Comment by ghost** [comment]
Does the user agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36` work? It's a valid user agent string and it will also satisfy your requirement to not spoof as Windows 10.

**Comment by ghost** [comment]
For whatsapp and discord, does the user agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0` work?

**Comment by the-r3dacted** [comment]
Probably

**Comment by the-r3dacted** [comment]
There's a new fork you could voice your concerns t- oh wait you deleted account fucking troll
