### ISSUE TITLE
Support for NT 6.0 / NT 5.x series

### ISSUE THREAD

**Issue by unclecaptain5426** [Eclipse-Community/r3dfox-old#129]
I tested r3dfox on Windows XP with One-Core API and worked for me.

![Windows XP x86 SP3-2024-07-17-14-15-48](https://github.com/user-attachments/assets/061a2e7c-35e8-4884-879a-c3d7432f809d)

What if you can add r3dfox support for Windows Vista / XP without Extended Kernel + Windows 2000 SP4 with Extended Kernel?

Windows Vista SP2 without Extended Kernel: K32EnumProcessModules missing in kernel32.dll
Windows XP SP3 without One-Core API: AcquireSRWLockExclusive missing in kernel32.dll
Windows 2000 SP4 with Extended Kernel: RtlSetLastWin32Error missing in ntdll.dll.

**Comment by the-r3dacted** [comment]
I'll soon make r3dfox ESR 128 with support for Vista. Currently there is the old 126 release and the 115 ESR release.

No idea about 2000 though.

**Comment by FlorianisonGitHub** [comment]
Why not XP?

**Comment by the-r3dacted** [comment]
Vista is easy in comparison to what will be needed for XP.

**Comment by unclecaptain5426** [comment]
Will Eclipse r3dfox ever support Windows Vista, Windows XP, and Windows 2000 with Extended Kernel?

**Comment by unclecaptain5426** [comment]
What about adding support for Windows XP?

**Comment by the-r3dacted** [comment]
> Will Eclipse r3dfox ever support Windows Vista, Windows XP, and Windows 2000 with Extended Kernel?

If I get it perfect, the main version might. The current issue is the sandbox doesn't work on Vista 32 bit, but the browser is otherwise good.

I assume XP will be relegated to second release or ESR if it happens as that might be a bit much.

**Comment by ghost** [comment]
For XP, let's wait for @win32ss's Superfox.

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.2

**Comment by T5NH** [comment]
For XP there is MyPal https://github.com/Feodor2/Mypal68/releases

**Comment by the-r3dacted** [comment]
Closing this as it's less relevant compared to this issue focused solely on XP.

https://github.com/Eclipse-Community/r3dfox/issues/151

**Comment by matthewbs10** [comment]
What about Windows 98, Me with Extended kernel and maybe ram management for these systems,
