### ISSUE TITLE
Widevine plugin missing 

### ISSUE THREAD

**Issue by marty60** [Eclipse-Community/r3dfox-old#133]
What I did was copy over the profile from Firefox 128.0 in Windows 10 and everything works perfectly except Widevine is missing in the about:addons dashboard. Is this plugin compatible with r3dfox? It's enabled in about:config and has the latest version 4.10.2710.0.

**Comment by the-r3dacted** [comment]
Normally I would say I don't build with DRM and I never will. However lucky for you, less than an hour ago, a fork built with DRM released, and it needs testing. If it's broken, make an issue there.

https://github.com/lunanakaya/luminafox/releases/tag/128.0.2-rc1

**Comment by marty60** [comment]
That was fast, I barely even had to time to re-check my post :). I'll take a look at that build thanks as I do like to watch youtube movies on occasion.

**Comment by marty60** [comment]
I'll take a look at that build thanks as I do like to watch youtube movies on occasion.

**Comment by krystian3w** [comment]
I think this have all bugs like unpaid Google licence other forks (disabled streaming/VoD or in SD quality): https://github.com/win32ss/supermium/issues/699

**Comment by marty60** [comment]
> I think have all bugs like unpaid Google licence other forks (disabled streaming/VoD or in SD quality): [win32ss/supermium#699](https://github.com/win32ss/supermium/issues/699)

Builds with L3 quality would still be better than nothing but 115.0 should keep working for a while yet on Win7.

**Comment by mausalimi** [comment]
luminafox seems to be dead already....

**Comment by krystian3w** [comment]
Test these Snowfox https://github.com/adeii/supermium-portable/releases/tag/F135 - Unfortunately adeii a bit of garbage in the releases with other browsers (so don't suggest the name of the repository).

**Comment by mausalimi** [comment]
> Normally I would say I don't build with DRM and I never will. 

Why is that? My internet provider uses this for streaming, so there is no way for me to use redfox.

**Comment by the-r3dacted** [comment]
I just don't like having the closed source component in my browser.

If I don't enable in Plasmafox or whatever, you could use this fork instead ig.

https://github.com/e3kskoy7wqk/Firefox-for-windows-7/

**Comment by mausalimi** [comment]
Thank you, that's the one i am using right now.
What i do not exactly like there, it usually has no compiles of the "stable" versions, and i am not a huge fan of Firefox nightlies. Ah well. :)

**Comment by the-r3dacted** [comment]
I might enable DRM in an alternative build, but that would be like an extra 2:30 for building. Maybe I could use it to release as a test build without PGO idk. Or I could turn one of my PCs into a build server and not need to think about it too much idk.

**Comment by mausalimi** [comment]
Uh... i had no idea it takes THAT long to build. I guess it's too big to let it build at GitHub actions.

**Comment by the-r3dacted** [comment]
Ok so it's like ~30 minutes to build without PGO,, ~60 minutes for both x86 and x64. This might be fine to release, but it will be slower than a full release build.

With PGO the build time is ~70 minutes per build, ~140 minutes for both x86 and x64.

This is with 8c16t allocated from my 5950X. Firefox doesn't seem to scale that much past 8c16t. It has the capability to, but it likes to just build something with rustc for like 20 minutes on one core which kills any gains from the extra cores.

I might try dropping my VM to 6c12t and see if that has any impact.

Edit: Going down to 6c12t does slow down the build by 6-7 minutes.
