### ISSUE TITLE
Problem with userchrome on latest build

### ISSUE THREAD

**Issue by mjdbb1** [Eclipse-Community/r3dfox-old#135]
Hi there.  Just updated to 128.0-2 and now having an issue with userChrome.  I'm using this:

https://github.com/Aris-t2/CustomCSSforFx

Worked fine on 128.0 with no problems, but now the same config looks like this: 
![sample2](https://github.com/user-attachments/assets/600ff83e-210a-414c-8314-bdb111244d55)

Should look like this (did on 128.0):
![sample1](https://github.com/user-attachments/assets/27988b50-0742-43d9-8517-c558bfd53a2d)

Any thoughts or relevant changes?

**Comment by the-r3dacted** [comment]
Disable Use r3dfox theme styles and Use r3dfox colors in settings.

**Comment by mjdbb1** [comment]
Oh cool.  Thanks!  :)
