### ISSUE TITLE
Built-in translator doesnt work

### ISSUE THREAD

**Issue by JonnyThree** [Eclipse-Community/r3dfox-old#136]
Hello i've installad in my Win 7 x64 setup the latest [Release v128.0.2 for Vista+](https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.2)

the built-in translator doesnt work, no popup window, and also no icon on the url address bar.

this bug is not present in [Release v128.0-2](https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0-2)

**Comment by the-r3dacted** [comment]
I'll look into this the version after the next (so 128.0.2-3 or 128.0.3)

**Comment by the-r3dacted** [comment]
Will be fixed in 128.0.3

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.3

**Comment by JonnyThree** [comment]
thanks i will try it
