### ISSUE TITLE
Remove unnecessary space in theme

### ISSUE THREAD

**Issue by Jevil7452** [Eclipse-Community/r3dfox-old#139]
In the r3dfox theme, there is a pretty unnecessary gap in the r3dfox theme.
Like so:
![image](https://github.com/user-attachments/assets/b1e60b02-4b7f-489b-8a20-e82869c8743a)
It's even more obvious when the user has the titlebar/menubar enabled
![image](https://github.com/user-attachments/assets/264d8463-7e93-47b8-8105-3f65eab75538)
The browser doesn't make use of the space gained on the right of the caption buttons at all. (in the mode when there's no titlebar/menubar)
This also doesn't occur with the regular Firefox theme.

**Comment by the-r3dacted** [comment]
I added that for drag space, I completely forgot the menu bar was a thing. I'll add a toggle or find a better solution next release.

**Comment by the-r3dacted** [comment]
Supposedly I made "all dom mutations slower" whatever that means, but it is fixed for 128.0.3.

The drag space goes away with the menubar.

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.3
