### ISSUE TITLE
Have found the answer that portable version can't be set for the default browser

### ISSUE THREAD

**Issue by nomosaic** [Eclipse-Community/r3dfox-old#145]
There is no directory“uninstall” file“helper.exe” in portable version.
I download the installer version, unpack that directory and file from it into the program root directory, re-set, it works.

**Comment by jonm58** [comment]
Because the installer has registry settings, this is a useless issue.
close this issue

**Comment by the-r3dacted** [comment]
So, I assumed helper.exe was not required since there's no installer. I guess that was wrong. I'm about to release 129 and I'll leave it in.
