### ISSUE TITLE
Gratitude and great thanks and donations 

### ISSUE THREAD

**Issue by trimechee** [Eclipse-Community/r3dfox-old#147]
Hello, i discover today the amazing great R3dfox and i would like to thank you so much @Eclipse-Community  for our beloved the saver life so useful vital great marvellous R3dfox web browser ! 💯 🥇

because my main laptop broke down recently and I went back to using my old laptop from year 2012 and so R3dfox  is very useful vital and saves my machine from destruction !

Many thanks again for the great @Eclipse-Community  for all your efforts to support the millions of machines that still under windows 7 32 bits and thus save the ecology and our wallets and economy !

and i suggest to make donations button paypal or buy me coffe or block chain.....in the main home page of R3dfox to support the great developer(s) and help develop and maintain this essential magnificent project :)

**Comment by the-r3dacted** [comment]
I appreciate the words, even though I'm finally getting to this basically 24 hours later. I was too tired at the time you posted, even though I am probably too tired now. Not enough time to get around to this.

> and i suggest to make donations button paypal or buy me coffe or block chain.....in the main home page of R3dfox to support the great developer(s) and help develop and maintain this essential magnificent project :)

I might look into this, but what exactly do you mean? I have this linked in the About r3dfox window. https://board.eclipse.cx/viewtopic.php?t=657 Should I put it somewhere else too?

**Comment by trimechee** [comment]
I was so pleasantly surprised, astonished, shocked to find R3dfox based on the latest version of firerox while even mozilla the big company does not provide 32 bit firefox for windows 7 that I wrote my thank you message before even installing R3dfox lol! I am currently testing r3dfox and it is perfect fast, thank you very much! and I think donations linked in the About r3dfox window is the ideal and perfect! thank you so much for this aweome browser :)

**Comment by the-r3dacted** [comment]
![yay1](https://github.com/user-attachments/assets/7436c657-55e6-450a-a8f2-5544456a6ff4)
