### ISSUE TITLE
STOP SENDING YOUR UGLYASS EMOJIS IN DISCORD

### ISSUE THREAD

**Issue by notharold** [Eclipse-Community/r3dfox-old#148]
GO SHUTUP IN THE DISCORD SHUTUP!!!!!!!!!!!!!!!!!!!!

**Comment by notharold** [comment]
gooooo
GOOOOOOOOOOOOOOOOOOOO

**Comment by notharold** [comment]
BROOOOOO GO DIE

**Comment by the-r3dacted** [comment]
> BROOOOOO GO DIE

![907420016536866826](https://github.com/user-attachments/assets/eb55dc21-ebac-4ffd-9e7a-561eaaa2bda1)
