### ISSUE TITLE
Google Maps rendering problem

### ISSUE THREAD

**Issue by drajko88** [Eclipse-Community/r3dfox-old#150]
Testing r3dfox releases 128.0.3 & 129 on Win7 Pro SP1 (build 7601) I  found a problem with opening Google Maps (https://maps.google.com/), it won't render, showing just controls & blank map placeholder. Embedded maps the same- try https://www.meteoblue.com -> Weather Maps. Also on https://get.webgl.org/ "Your browser supports WebGL" but there's no spinning cube. On Firefox 115 and Supermium (a Chromium fork) everything works as expected. I've tried about everything I could think of on the fresh unpacked browser ,no customisations, no extensions , so far no luck

https://github.com/user-attachments/assets/077ef309-8f2b-499d-8aba-36f7054fb660

<img width="946" alt="2024-08-07_085357_cr" src="https://github.com/user-attachments/assets/dcaf90a3-36fd-45bb-9ded-10865f51509d">

r3dfox:
<img width="338" alt="r3dfox graphics 2024-08-07_130609" src="https://github.com/user-attachments/assets/82c0af63-692d-49f2-8624-6d4ee2bf6d01">
firefox:
<img width="273" alt="ffx graphics 2024-08-07_130247" src="https://github.com/user-attachments/assets/9dd86a12-23bf-45e9-a69a-d77f39be29b8">

Any idea?

**Comment by jonm58** [comment]
why is sotware d3d11 Render,not hardware Render?
![图片](https://github.com/user-attachments/assets/de311534-b406-444c-9e0a-94a6f6a91a42)
![图片](https://github.com/user-attachments/assets/3a7f5113-4627-4606-af36-ecec8d452075)

**Comment by drajko88** [comment]
I have no clue about it, "Use hardware acceleration.." is ticked on, my Firefox 115 is way older and working ok

**Comment by DoctorVovhu** [comment]
I don't have these problems. Windows 7(6.1.7601) Bits: 32. DirectX: 9.0c(4.09.00.0904). Direct3D 9Ex: OK
![Screen-717](https://github.com/user-attachments/assets/9b85c8ab-c61f-4de2-bb90-c9e5b8d47e71)
![Screen-718](https://github.com/user-attachments/assets/3c3d8f4f-2506-4590-aae9-60620d3ab952)
![Screen-719](https://github.com/user-attachments/assets/a106d7e5-1626-4d96-80cc-e34aac868b7a)

**Comment by the-r3dacted** [comment]
Can you send the full about:support page here pls? Also your GPU model too.

**Comment by DoctorVovhu** [comment]
K4sum1, who are you asking? drajko88 or DoctorVovhu?
![55](https://github.com/user-attachments/assets/b429a8cc-7ef3-480a-8365-21ea1587e780)

**Comment by drajko88** [comment]
[rd3fox about_support.txt](https://github.com/user-attachments/files/16531902/rd3fox.about_support.txt)

I just spotted:
---
Failure Log
(#0) Error: Failed to connect WebRenderBridgeChild. isParent=true
(#1) Error: Fallback WR to SW-WR + D3D11
(#2): GP+[GFX1-]: Failed to link shader program: gpu_cache_update
(#3): GP+[GFX1-]: wr_window_new: Shader(Link("gpu_cache_update", ""))
---
?!

**Comment by drajko88** [comment]
[rd3fox about_support.txt](https://github.com/user-attachments/files/16531902/rd3fox.about_support.txt)

I just spotted:
---
Failure Log
(#0) Error: Failed to connect WebRenderBridgeChild. isParent=true
(#1) Error: Fallback WR to SW-WR + D3D11
(#2): GP+[GFX1-]: Failed to link shader program: gpu_cache_update
(#3): GP+[GFX1-]: wr_window_new: Shader(Link("gpu_cache_update", ""))
---
?!

**Comment by drajko88** [comment]
I just tried enabling "gfx.webrender.compositor.force-enabled" - no joY :(

**Comment by the-r3dacted** [comment]
Well, I guess test r3dfox builds until you find the last to work.

**Comment by jonm58** [comment]
> [rd3fox about_support.txt ](https://github.com/user-attachments/files/16531902/rd3fox.about_support.txt)
> ## 我刚刚发现：
> ## 失败日志
> (#0) 错误：无法连接 WebRenderBridgeChild。 父级=true
> ( [ Eclipse-Community/r3dfox#2 ](https://github.com/Eclipse-Community/r3dfox/issues/1) ) 错误：回退 WR 至 SW-WR + D3D11
> ( [ Eclipse-Community/r3dfox-old#2 ](https://github.com/Eclipse-Community/r3dfox/issues/2) ): GP+[GFX1-]: 无法链接着色器程序: gpu_cache_update
> ( [ Eclipse-Community/r3dfox-old#3 ](https://github.com/Eclipse-Community/r3dfox/issues/3) ): GP+[GFX1-]: wr_window_new: Shader(Link("gpu_cache_update", ""))
> 
> ?!

Can you send the full about:support page here pls? Also your GPU model too.

**Comment by jonm58** [comment]
> DirectX: 9.0

firefox only support dx11,r3dfox too,you are use DX11(D2D) hardware acceleration

**Comment by drajko88** [comment]
I'll keep on trying because I really like r3dfox as idea and the browser is damn good :)

@jonm58: here's the full screenshot

<img width="947" alt="r3dfox about_support 2024-08-07_191443" src="https://github.com/user-attachments/assets/53bbe807-13c7-47ba-ac76-34e0663e30f5">
