### ISSUE TITLE
R3dfox stops working after a few seconds, on startup

### ISSUE THREAD

**Issue by trimechee** [Eclipse-Community/r3dfox-old#152]
Hello, when I open our beloved R3dfox in my windows 7 os 32 bits starter edition, , after a few seconds, R3dfox displays a message "R3dfox has stopped working, there is a malfunction....close the program ?" I close R3dfox and I open it again, there is a message we have trouble restoring your session, I choose once to restore the session, another time not to restore the session and the same bug starts again and again ....

I have not changed the default settings of R3dfox,, and I have not installed any extensions, I just disabled the windows user account controller because I had to do that so that firefox esr 115 allows me to make desktop shortcuts by drag and drop...

R3dfox doesn't have native integrated logs / crash report tool please ?

**Comment by the-r3dacted** [comment]
Weird. Do you happen to have ESU by chance? Also can you find the last version to work?

**Comment by trimechee** [comment]
What does mean ESU please ? i install Release v129.0 for Vista+

**Comment by the-r3dacted** [comment]
ESU are paid updates after 2020. There might be a bug related to them.

Also try upgrading your VC++ redist.

**Comment by trimechee** [comment]
Thank you for your advices :) I have Redistributable Visual C++ for Visual Studio 2015 14;40.33810, I don't use ESU, the last windows update in my asus eee pc is from year 2016, then windows updater does not work anymore in my os, I disabled the antivirus, the firewall, windows compatibility monitoring service ..... to make my laptop faster, and recently I set the startup type of microsoft net framework v4 to manual instead of automatic .... I also have microsoft net framework v2, and firefox esr 115 works normally without problem

**Comment by the-r3dacted** [comment]
I'm not sure then. Try older versions until you find the last to work I guess.

**Comment by trimechee** [comment]
i even added to R3dfox shorcut :
-no-deelevate

--disable-launcher-process
 and i didn't find browser.launcherProcess.enabled false in about:config of R3dfox

**Comment by trimechee** [comment]
Thank you :) i will try Liminafox :)

**Comment by trimechee** [comment]
There is no telemetry tool in R3dfox to send the bug data to the developer?

**Comment by the-r3dacted** [comment]
idk how to solve crashes without replicating it myself and bisecting.

**Comment by trimechee** [comment]
I specify I use an administrator account, for the moment I had an idea, right click on the desktop shortcut of R3dfox, advanced, run as administrator, for the moment I test and the malfunction message no longer appears, for the moment, so I continue to test, in any case thank you for your help :)

**Comment by trimechee** [comment]
Hi,  right click on the desktop shortcut of R3dfox/advanced/ run as administrator= my tip seems to have fixed this bug, because R3dfox seems to have problems when using an administrator account....

for now I'm closing this issue since this bug seems to have disappeared but I'm continuing to test with a view to making ur beloved R3dfox my main web browser in sha Allah :) i also disabled use native styles and R3dfox theme styles...may disable these settings fixes the problem...

Thank you :)
