### ISSUE TITLE
Doesn't work again DNS over HTTPS.

### ISSUE THREAD

**Issue by DoctorVovhu** [Eclipse-Community/r3dfox-old#153]
Doesn't work again DNS over HTTPS in v.129-2.
![111](https://github.com/user-attachments/assets/1a9207c0-27f2-43fe-8e2b-8fc6765d47aa)

**Comment by jonm58** [comment]
> Doesn't work again DNS over HTTPS in v.129-2. ![111](https://private-user-images.githubusercontent.com/177610677/356197718-1a9207c0-27f2-43fe-8e2b-8fc6765d47aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTc4ODcsIm5iZiI6MTcyMzExNzU4NywicGF0aCI6Ii8xNzc2MTA2NzcvMzU2MTk3NzE4LTFhOTIwN2MwLTI3ZjItNDNmZS04ZTJiLThmYzY3NjVkNDdhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTQ2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmZmMjRmNjUzMDM5ZjM2NDhjMWIyZTE3ODY5MDZiZDZmMDRhYmM4ZmVjYTRmZWU0ODRjZDI3MTBhM2FjZjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pB_mrsw94ir-OGItoR0x6ypLZE36fRNRrolU7OVZ70Y)

windows 11 too

**Comment by the-r3dacted** [comment]
I undid the fix for 129 since Mozilla knows the issue and they should be fixing it, but I guess I'll add it back for 129.0-3 or 129.0.1. I don't get why these settings are that important when it adds the security equivalent of wet toilet paper, but sure.

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/releases/tag/v129.0-3
