### ISSUE TITLE
about language

### ISSUE THREAD

**Issue by jonathanhzs** [Eclipse-Community/r3dfox-old#155]
Reserve a language file interface for setting up the parts of it that are specific to r3dfox.

**Comment by jonathanhzs** [comment]
It is best to use a simple ini file to make it easy for users to make their own

**Comment by the-r3dacted** [comment]
I'm not touching language stuffs when I don't know anything other than English. I would have no idea what to do.

**Comment by jonm58** [comment]
@jonathanhzs why you not make langpack-zh-CN's xpi,lmao

**Comment by jonathanhzs** [comment]
![QQ拼音截图20240814102927](https://github.com/user-attachments/assets/e232c218-d9a0-44e4-833c-0e250af6ec63)
Of course

**Comment by jonathanhzs** [comment]
the area is getting bigger and bigger！

**Comment by the-r3dacted** [comment]
I'll eventually make it into another thing on the side.
