### ISSUE TITLE
Add ability to disable CORS

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#158]
Might fix this issue
https://gist.github.com/XiaoPanPanKevinPan/3cceb1d84ea97c04fe17ad087df8def6?permalink_comment_id=5151671#gistcomment-5151671

**Comment by jonm58** [comment]
content.cors.disable?

**Comment by jonm58** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDisabled

"A request that needs to use [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS) was attempted, but CORS is disabled in the user's browser. When this happens, the user needs to turn CORS back on in their browser.

In Firefox, the preference that disables CORS is content.cors.disable. Setting this to true disables CORS, so whenever that's the case, CORS requests will always fail with this error."
