### ISSUE TITLE
Turning off the menu bar renders the browser unusable, crashes on launch

### ISSUE THREAD

**Issue by Glossaryck** [Eclipse-Community/r3dfox-old#159]
I'm currently running r3dfox version 129.0.1 on Windows 7 Professional SP1 (fully updated to January 2020, non-ESU).
On a new installation, I went to turn off the menu bar, and the browser crashes; after which it keeps immediately crashing on launch, rendering the browser unusable.

Crash log provided by Windows: 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	r3dfox.exe
  Application Version:	129.0.1.643
  Application Timestamp:	66bb88b3
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24545
  Fault Module Timestamp:	5e0eb6bd
  Exception Code:	c06d007e
  Exception Offset:	000000000000b87d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	fabd
  Additional Information 2:	fabddded1baaa1f0125084edf693bcbb
  Additional Information 3:	df0e
  Additional Information 4:	df0e87cf6c110c5315ed4db28df4892d

**Comment by Glossaryck** [comment]
Sometimes the browser comes up with this message telling me to launch it in Safe Mode, but it also immediately crashes on launch in Safe Mode.
![image](https://github.com/user-attachments/assets/d7bd8980-d1d4-4278-a4f9-5e1d420296eb)

**Comment by the-r3dacted** [comment]
I'm unable to replicate on any install, hardware or VM.

Someone else had a weird issue with crashing without ESU, and supposedly running as administrator fixed it. What happens if you try to run as admin?

**Comment by Glossaryck** [comment]
> I'm unable to replicate on any install, hardware or VM.
> 
> Someone else had a weird issue with crashing without ESU, and supposedly running as administrator fixed it. What happens if you try to run as admin?

I did not immediately try to run the browser as admin, instead I went back to version 129.0-4 and the bug magically went away. I have since updated to 129.0.1 and the bug did not come back.
