### ISSUE TITLE
Request for x86(32bit) build in next release

### ISSUE THREAD

**Issue by fylgjagh** [Eclipse-Community/r3dfox-old#16]
My Windows 7 is x86(32bit) because running 16bit apps on NTVDM.

**Comment by jonm58** [comment]
> 16bit apps

https://github.com/otya128/winevdm

**Comment by the-r3dacted** [comment]
Probably will do that soon, but not sure when exactly. I would like to get it 100% before I start doing a bunch, but I have no idea when or if I will get it 100%.

Maybe when 123 comes I'll try x86 build.

**Comment by adeii** [comment]
x86 build should be easy, just add line
ac_add_options --target=i686
to mozconfig. 
Tested on nightly 125.0a1 with your patches for 122 - works on Win 8.1 and Win 7.

**Comment by uxmy** [comment]
+1 for 32-bit build.

**Comment by Ryosuke-Asano** [comment]
@K4sum1 We build a script for building Firefox for windows 32bit.

https://github.com/Floorp-Projects/Floorp/blob/ESR115/.github/workflows/windows-build.yml

**Comment by adeii** [comment]
You can try portable Firefox 32bit or better say R3dfox-without-branding
https://github.com/adeii/supermium-portable/releases/download/F1235/Firefox-portable-win32-123.0.2-win7.7z

Update:
R3dacted Fox 124.0 32bit
https://github.com/adeii/supermium-portable/releases/download/F1235/r3dfox-124.0.en-US.win32.zip

**Comment by fylgjagh** [comment]
r3dfox-124.0.3.en-US.win32.installer.exe
 Firefox-portable-win32-124.0.1-win7.7z
![rf124](https://github.com/Eclipse-Community/r3dfox/assets/139169240/9df096ea-a354-45a4-860e-87c789e5feb5)
Thank you for @K4sum1 and @adeii  !
