### ISSUE TITLE
Portable builds - extensions configuration somehow breaks after running R3dFox from a Windows installation that is different from the previous one

### ISSUE THREAD

**Issue by Sevoos** [Eclipse-Community/r3dfox-old#163]
Running it on 7 after 10, or the reverse, doesn't matter. After clicking the "extensions" button on the toolbar, it sends you to about:addons. where all the extensions are shown as enabled (and they don't function actually). Disabling them int hat menu, re-running the browser and enabling them fixes the issue (the button described above starts working normally - shows the list of enabled extensions while staying in the current tab) until the next run from another Windows installation.

**Comment by the-r3dacted** [comment]
I was hoping portable mode wouldn't have this issue, but I guess it does. This started happening at some point in old Firefox versions, but it's weirdly inconsistent and I'm not sure how to consistently trigger it to properly trace and fix it.

**Comment by Sevoos** [comment]
> I was hoping portable mode wouldn't have this issue, but I guess it does. This started happening at some point in old Firefox versions, but it's weirdly inconsistent and I'm not sure how to consistently trigger it to properly trace and fix it.

I've found something that seems to be working! [Link](https://github.com/InfernoDungeon/firefox-portable-profile-fix)

However, it's only temporary. Just partially automated, but not a solution. It can't fix absolute drive letters forever

**Comment by Sevoos** [comment]
The main doom is the paths in profile\extension.json being absolute, and the drive letters being different in 2+ Windows installations. It can be fixed in my case, but it seems like portable builds need deeper editing

**Comment by the-r3dacted** [comment]
I found this

https://gitlab.torproject.org/tpo/applications/tor-browser/-/commit/c95f4a40ff1050693436db0da5fcd0b5a680fbfb

If I can remember, I'll try to get it into 128.3.0 and 130.0

**Comment by the-r3dacted** [comment]
Should be fixed in 130.0.1rc

https://github.com/Eclipse-Community/r3dfox/releases/tag/v130.0.1rc

**Comment by the-r3dacted** [comment]
Just going to close it rn, if it's broken lemme know
