### ISSUE TITLE
Missing Geo location.

### ISSUE THREAD

**Issue by lvpha** [Eclipse-Community/r3dfox-old#164]
Browser Geolocation fails even when I manually set the coordinates. I understand that the world is better without this setting. But, some work apps need it unfortunately. 

![image](https://github.com/user-attachments/assets/e3b8ef1f-1b09-4b22-85b5-e1a5ad5c16dd)

![image](https://github.com/user-attachments/assets/51b3957e-323c-4411-87c6-88eed46918c3)

And of course. Thank you so much for your work!

**Comment by the-r3dacted** [comment]
I'm not sure what would cause this to be an issue. Can you test previous versions to see where it began?

**Comment by lvpha** [comment]
Hey @K4sum1 , Thanks for your reply! 

Can I test portable versions, or I should install the .exe file (I am currently on installable version)?

**Comment by the-r3dacted** [comment]
Portable versions use their own profile, it might be best since it will complain about downgrading profile. (Although you can just delete compatibility.ini in profile folder and it should be fine)

**Comment by lvpha** [comment]
On 127.0.2 (32-bit) portable still fails.

**Comment by lvpha** [comment]
Same on the 124.0.3 (64-bit) installable.

**Comment by jonm58** [comment]
https://support.mozilla.org/en-US/questions/1293707
location.services.mozilla.com is dead
google geolocation need api key

**Comment by the-r3dacted** [comment]
> https://support.mozilla.org/en-US/questions/1293707 location.services.mozilla.com is dead

Actually I found what is probably the real reason there.

```
Note that the MOZILLA_API_KEY isn't included in third-party builds like used when you install Firefox from the repositories.
You can check this via the "Help -> Troubleshooting Information" (about:support) page.
You would have to use Firefox from the Mozilla server.
```

That would explain it. Another thing to tack onto shit unavailable to forks.

**Comment by lvpha** [comment]
Good finding! 

Is there a way to pull the API key from an official Firefox and insert it into R3dfox? 

![image](https://github.com/user-attachments/assets/e49f5cf1-2d58-4d84-b8fe-8e880ca1830a)

**Comment by lvpha** [comment]
Or here: 

![image](https://github.com/user-attachments/assets/19ff7f43-180a-4150-8b26-f1ec4ae9e7c6)

**Comment by lvpha** [comment]
Sorry for the spam guys: 

I was able to enter the coordinates manually using this setting:

geo.provider.network.url 

data:application/json,{"location": {"lat": XXXXX, "lng": XXXXX}, "accuracy": 27000.0} 

where XXXXX are LATITUDE and LONGITUDE values. 

Thanks for your help.

You can close this if you want :))))
