### ISSUE TITLE
r3dfox_esr-115.13.0

### ISSUE THREAD

**Issue by Naytaco** [Eclipse-Community/r3dfox-old#165]
Question to the author.
In version r3dfox_esr-115.13.0.en-US.win64.portable the profile is created on the system drive in AppData - Local & Roaming.
In version r3dfox-129.0.1.en-US.win64.portable the profile is created in the browser folder. Why is that?
However, the release notice says everywhere: "The portable builds are fully portable, the profile directory is inside the browser folder. It does not touch appdata at all."

Operating system - Windows 7 x64 sp1.

**Comment by the-r3dacted** [comment]
Ok, so I messed up when making the portable releases. r3dfox portable mode is controlled by the existence or non-existence of pmundprt.mod in (r3dfox)\browser

I forgot to include pmundprt.mod in the portable release
