### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by TRX99** [Eclipse-Community/r3dfox-old#166]
Hello

I already installed the 128.0 (64-bit) version, but before installing it, I uninstalled the old version and deleted its folder. Now, when I upgraded to version 129.0.1, the version was correct, but after I closed it and opened it again, it shows version 128.0.

Thank you

**Comment by the-r3dacted** [comment]
You might still have the old version.

Go to Program Files, check for these folders: Eclipse Community\r3dfox, Eclipse r3dfox, Eclipse r3dactedfox, r3dfox, r3dactedfox. For every folder that exists, open it up, to to uninstall, and run helper.exe

After this is done, install 129.0.1, and it should be fixed.

**Comment by the-r3dacted** [comment]
Assuming fixed since no response.
