### ISSUE TITLE
ESR 128 requested.

### ISSUE THREAD

**Issue by clifford269** [Eclipse-Community/r3dfox-old#168]
Hey, it'd be great if you could at times also publish the ESR release, you know they only come out like once a month or so. That way it'd be easier to work with themes.

**Comment by the-r3dacted** [comment]
From what I can tell, ESR 128.2.0 should be in RC stage, so I'll be getting that out today. I actually built it yesterday, but I was too tired to wait for it to finish and upload.

**Comment by clifford269** [comment]
Well, thanks. Is there a way for me to have it built right from the source? It would be great if you provide some documentation on how you've backported FF to w7 systems.

**Comment by the-r3dacted** [comment]
So uh I kinda fucked up, the current version. So I'll have to rebuild.

> Well, thanks. Is there a way for me to have it built right from the source? It would be great if you provide some documentation on how you've backported FF to w7 systems.

If you undo all the Vista changes, it kinda just builds with the official instructions

**Comment by clifford269** [comment]
That's what I mean. If I could provide some documentation on what are the changes you made to make it Vista+ compatible, and perhaps also how the altered code would build, that'll be great.

**Comment by the-r3dacted** [comment]
> That's what I mean. If I could provide some documentation on what are the changes you made to make it Vista+ compatible, and perhaps also how the altered code would build, that'll be great.

I'll be making a new build VM soon, this will let me catalog every change I need to make from normal instructions.

Also 128.2.0rc out
https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.2.0rc
