### ISSUE TITLE
Windows 8.1 (and later) detected as NT 6.2 (8.0)

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#17]
Not sure what causes this, it's a known issue with some older software, maybe I didn't revert something correctly idk.

**Comment by jdev15** [comment]
I think it's related to this API call: https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw

> With the release of Windows 8.1, the behavior of the GetVersionEx API has changed in the value it will return for the operating system version. The value returned by the GetVersionEx function now depends on how the application is manifested.

> Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases. To manifest your applications for Windows 8.1 or Windows 10, refer to [Targeting your application for Windows](https://learn.microsoft.com/en-us/windows/desktop/SysInfo/targeting-your-application-at-windows-8-1).

**Comment by the-r3dacted** [comment]
I spotted the latest r3dfox release (122) has no manifest. 8.1 hasn't been removed from Firefox manifest as of yet. Not entirely sure what happened, but will investigate once I get around to making 123.
