### ISSUE TITLE
Where is the profile manager?

### ISSUE THREAD

**Issue by Jasantes** [Eclipse-Community/r3dfox-old#170]
**Where is the profile manager? 
I've tried a shortcut with [-p] or [-profilemanager] arguments but no way...!
Where is it?**

**Comment by the-r3dacted** [comment]
about:profiles?

**Comment by Jasantes** [comment]
**What I mean is how to select the profile BEFORE opening, like in Firefox and its forks.**

**Comment by the-r3dacted** [comment]
I didn't even know such a thing existed. If you can figure out where it broke in a previous version, I could look at it, but it's too low priority for me to want to look into.

**Comment by Jasantes** [comment]
Thanks for your reply. I really like **r3dfox**. 
Try with Firefox as I explained before and you will see that it is a very important feature. Shortcut target: **\firefox.exe -p**

**Comment by the-r3dacted** [comment]
Uh I guess that since it works on 129.0.1 that this is such a recent breakage that it might be upstream. I don't think any r3dfox 129.0.2 change would've done it.

![image](https://github.com/user-attachments/assets/3a5b68cc-9c27-478a-b19a-de2da224cffe)

**Comment by the-r3dacted** [comment]
uh works on my machine with latest
![image](https://github.com/user-attachments/assets/fb0e2861-381e-42ef-885f-5fa9c5646f47)

**Comment by Jasantes** [comment]
I have 128.0.2 (32-bit) and doesn't work.

**Comment by the-r3dacted** [comment]
Are you using the portable variant? Try deleting pmundprt.mod in the browser folder.

**Comment by Jasantes** [comment]
**Perfect... thank you very much and greetings from Uruguay!!!**

**Comment by the-r3dacted** [comment]
That makes sense. The portable mode means it doesn't touch AppData and it is in single profile mode, so -p wouldn't work.

**Comment by bonbonboi** [comment]
> Are you using the portable variant? Try deleting pmundprt.mod in the browser folder.

What happened technically when I delete "pmundprt.mod"?
