### ISSUE TITLE
Translucent design assumes the user has dark mode

### ISSUE THREAD

**Issue by Jevil7452** [Eclipse-Community/r3dfox-old#177]
![r3dfox-2024_09_07-18_47_48](https://github.com/user-attachments/assets/2d75ba79-b12a-4ccd-959d-b3462c505bdb)
Pretty much easily described with a screenshot. (I use Light mode)

**Comment by the-r3dacted** [comment]
Fixed in 130.0.1rc

https://github.com/Eclipse-Community/r3dfox/releases/tag/v130.0.1rc
