### ISSUE TITLE
Disaster catastrophe : Open-in-vlc no longer works with r3dfox web browser !

### ISSUE THREAD

**Issue by trimechee** [Eclipse-Community/r3dfox-old#178]
Hello, the great Open-in-vlc extension : 

https://github.com/andy-portmen/open-in-vlc

 is essential in our life and life saver because my old eee pc from the year 2012 lag freezes when I watch html5 streaming video in heavy web browser but i have smooth playback without jerks lags with vlc or potplayer, and R3dfox browser is almost the only web browser in the world to use the most recent firefox kernel for windows 7 32 bits so Open-in-vlc worked normally in R3dfx but today, I receive an astonishing message "native client discontinued" ...... I do not know if the error comes from native client or because the accessibility service is disabled at the source by R3dfox .....

Open-in-vlc is the most important extension in the history of humanity so we hope this bug will be fixed please :)

I specify recently I changed this flag to experiment on its effect on extensions but I just put the default value back and I retest: security.mixed_content.block_active_content false

the bizarre mysterious thing is Open-in-vlc worked fine in previous versions of r3dfox , but with the new updates of R3dfox, the connection with native client seems to have been cut aborted in a mysterious way.....

https://github.com/andy-portmen/native-client

i also contacted the developer of Open-in-vlc and even asked him to add a special support specific to our beloved R3dfox to try to find some clues and beginnings of answers to this capital mystery......

UPDATE : i make new test with official firefox esr browser with this link , Open in vlc works without bug in firefox esr  : 

https://v5.voiranime.com/anime/wistoria-wand-and-sword/wistoria-wand-and-sword-09-vostfr/

But this bug remains in r3dfox browser.....and we hope please in the future r3dfox compatible with windows 10 therefore the developer of Open-in-vlc extension can add specefic registry modifications of native client for r3dfox, thank you :)

**Comment by trimechee** [comment]
UPDATE : i make new test with official firefox esr browser with this link , Open in vlc works without bug in firefox esr  : 

https://v5.voiranime.com/anime/wistoria-wand-and-sword/wistoria-wand-and-sword-09-vostfr/

But this bug remains in r3dfox browser.....and we hope please in the future r3dfox compatible with windows 10 therefore the developer of Open-in-vlc extension can add specefic registry modifications of native client for r3dfox, thank you :)

**Comment by marty60** [comment]
Hello trimechee,

Have you tried a different extension? I originally had the Portman one but it lacks the ability to open certain links like shorts and the new live links. He also no longer allows in his newer versions to substitute other players. I use MPC-BE, which is far superior to VLC in streaming.

You might want to consider trying this one instead, it works fine in r3dfox, opens up the links I previously mentioned and lets you change the path to MPC-BE.exe instead.

https://addons.mozilla.org/en-US/firefox/addon/open-in-vlc-videolan/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

You do need to reinstall the native client (it's a different path) and you need the path added into the registry to make it work. If you decide to try it and want help getting it to work let me know and I'll upload everything.

**Comment by marty60** [comment]
Hello trimechee,

Have you tried a different extension? I originally had the Portman one but it lacks the ability to open certain links like shorts and the new live links. He also no longer allows in his newer versions to substitute other players. I use MPC-BE, which is far superior to VLC in streaming.

You might want to consider trying this one instead, it works fine in r3dfox, opens up the links I previously mentioned and lets you change the path to MPC-BE.exe instead.

https://addons.mozilla.org/en-US/firefox/addon/open-in-vlc-videolan/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

You do need to reinstall the native client (it's a different path) and you need the path added into the registry so it'll open. If you decide to try it and want help getting it to work let me know and I'll upload everything.

**Comment by trimechee** [comment]
Ohh very instrctive and interesting, thank you so much for your precious advice :) 💯 🥇 

the extension you suggested seems very promising and allows you to choose other media players other than vlc, thank you :)

for the moment, I have supermium, thorium legacy, yandex, catsxp which are compatible with windows 7 32 bits and there is no bug of open in vlc in chromium based browsers, and Open in vlc by Mr Andy is recently updated and added the referrer, user sring agent and updated the native client ...... and Mr Andy is very nice and accepts our suggestions and remarks .....

i have done tests with different sites, vlc is the best superior media player compatible with streaming sites, i have done tests with potlayer as a media player in Cat-catch preview settings and on some sites, it does not work .....

i suggest to use Cat catch extension , it is open source and you can choose potplayer as media player for preview or vlc and I asked the developers of Open in vlc and Cat catch to add support for other media players!
https://github.com/xifangczy/cat-catch

if there are bugs in chromium or in the extensions or vlc and potplayer, then I will use the wonderful extension you suggested and I will let you know to help me install this extension, thank you very much Mr @marty60  :)

for now, I think the bug is in the browser because with firefox esr, there is no bug.....

**Comment by trimechee** [comment]
Hi Mr @marty60 , here the important advice of Mr Andy to make batch script and therefore, may be you will be able to play shorts and live links with oter media players like mpc be ou mpc hc :  

https://github.com/andy-portmen/open-in-vlc/issues/65#issuecomment-2316990741

**Comment by marty60** [comment]
Thanks for link, I didn't know that was possible. Might need it for Chrome/Edge when only Manifest V3 works. Firefox is keeping Manifest V2 so older extensions should be ok.

**Comment by trimechee** [comment]
Exactly, thank you :)

**Comment by the-r3dacted** [comment]
Try 130, should work now after enabling accessibility through the new GUI option.

https://github.com/Eclipse-Community/r3dfox/releases/tag/v130.0.1rc

**Comment by trimechee** [comment]
Great ! Thank you ! 💯 🥇 

Just to note the developer of Open in vlc told me he doesn't think that disabling accessibility service will affect the normal operation of native client but he also told me to do some tests to check.....

 in addition I disabled the flag: "auto disable accessibility when not needed" in chromium browsers and native client works without problem......

personally I think reintroducing accessibility service and making its deactivation optional is great and better because maybe some rare programs need this service and activating/reactivating this accessibility service quickly in about:config  allows us to test and verify...

Thank you very much and I will test the new version and inform you of the result :)

**Comment by trimechee** [comment]
Oops, sorry, I just checked and found out that the problem with native client of the Open in vlc extension is due to my clumsiness and forgetfulness :(

I recently installed zoom player and changed the path of vlc player for the zoom player path, and then I uninstalled zoom player and forgot to change the path for vlc player in Open in vlc ....

so it seems that accessibility service did not cause this problem but we still hope that R3dfox in the next versions will keep the possibility and the new feature to enable or disable acessiblity service, thank you very much :)
