### ISSUE TITLE
sidebar lost

### ISSUE THREAD

**Issue by jonm58** [Eclipse-Community/r3dfox-old#179]
![图片](https://github.com/user-attachments/assets/4fc9c1fa-c4a2-45d4-ad5c-94d589dd27ce)
![图片](https://github.com/user-attachments/assets/34f68141-bf70-43d7-8092-02ec8463174e)
please fix

**Comment by the-r3dacted** [comment]
I'm not sure what's wrong here.

**Comment by krystian3w** [comment]
I guess normal Firefox has a sidebar opened every time then we check to activate AI in it.

Unfortunately, I cannot verify this at the moment (We can use VMs with 10/11 if at 8.1 the Firefox 130 maybe started locks opening tightened).

On my side with R3dfox at Windows 7, the sidebar opens once and can be opened with a shortcut to the sidebar history and bookmarks (by changing it to AI in the header) or after click "show sidebar" button (Maybe Mozilla will add a dedicated shortcut/button in the future without bought keyboard with Copilot button).

**Comment by the-r3dacted** [comment]
Didn't know they added a sidebar, interesting.

**Comment by krystian3w** [comment]
The advantage is definitely that network traffic can be filtered using uBo MV2 (add-ons for opening any page or bookmark in sidebar make it impossible without uBo legacy or hotfix) - supposedly each of the AIs present there has some telemetry, blocked by "EasyPrivacy" (maybe too by AdGuard Tracking Protection list ) or "uBo - Privacy Filters List".

**Comment by jonm58** [comment]
Firefox 132.0a1
![图片](https://github.com/user-attachments/assets/7682e551-0b0a-4500-8440-c7ae2a87c0fc)

**Comment by the-r3dacted** [comment]
I have no idea how to get a sidebar like that

**Comment by jonm58** [comment]
> I have no idea how to get a sidebar like that

Can you compile 132.0a1, testing only
Maybe I got the wrong version

**Comment by the-r3dacted** [comment]
Unless someone helps me with Plasmafox (nightly r3dfox) I'm probably not going to do that. I would want to automate Windows builds after I rebase using GitHub Actions.

**Comment by T5NH** [comment]
It looks like this: https://winaero.com/firefox-enable-vertical-tabs/
@jonm58 try playing with **sidebar.revamp** and **sidebar.verticalTabs** in **about:config**

**Comment by jonm58** [comment]
> It looks like this: https://winaero.com/firefox-enable-vertical-tabs/ @jonm58 try playing with **sidebar.revamp** and **sidebar.verticalTabs** in **about:config**

![图片](https://github.com/user-attachments/assets/8fd37751-b976-4d6a-b011-af7cfd431544)
thanks you,that works
