### ISSUE TITLE
123 version does not work on 7

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#18]
So 123 is pretty much done, except it does not work on Windows 7. It opens for a split second before crashing. 8.1 is fine, 8.0 untested. Not sure what would cause this. I thought it was maybe the sandbox commit I marked as potentially maybe causing issues on 7, but I fiddled with that and I don't think that's the issue.

Not sure where to begin fixing this, aside from maybe modifying and building 123 alpha builds which would take way too long. Maybe I could filter through every commit between 122 and 123, but this far post 7 support removal, I don't think I would find it. Maybe building a debug build of some sort, but for now I want to return to working on my Android stuffs.

Also @Alex313031 please help.

Here's the 123 release without any branding, compiled with a basically stock mozconfig. Maybe it could be useful in figuring out the issue idk.
https://files.catbox.moe/uim5io.zip

**Comment by adeii** [comment]
Those the same 3 libs makes problem on Win 7 - xul.dll, mozglue.dll and lgpllibs.dll copied from release 121/122 makes even 124.0.a1 (nightly) running on Win 7 x64. 
Maybe x86 version could works better, since x64 versions of newer Chrome make hug memory bug, but x86 version don't.

Update:  firefox.exe and mozglue.dll are not problem in this case.
If lgpllips.dll and xul.dll  are from your r3dfox 122.0.1 and xul.dll is modded as 123.0.1 instead of 122.0.1, your 123 build is working on Win 7 x64, too.

https://ufile.io/p3qb865c 

Youtube video cause this warning:
[Child 7232, MediaDecoderStateMachine Eclipse-Community/r3dfox#2] 
WARNING: 9199a20 Could not set cubeb stream name.: file C:/ff/mozilla-unified/dom/media/AudioStream.cpp:320
JavaScript warning: https://www.google.com/js/th/fSwQ49dNtQ0TRgWZKHlAIhVKPl4K4-2hZ-2qmgklZeM.js line 2 > eval line 5996 > eval line 1 > eval line 1 > eval, line 1: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.

**Comment by the-r3dacted** [comment]
Welp Android stuff being fussy and I have some time, so investigating some. Merging into old 122 was actually kinda easy so doing that as sanity check. Then I should be able to git bisect and see what commit of 123 broke something.

**Comment by Alex313031** [comment]
@adeii When did they make sse4 a requirement?

**Comment by adeii** [comment]
> @adeii When did they make sse4 a requirement?

Sorry, wrong conclusion. That was for newer Waterfox, not Firefox. https://www.reddit.com/r/waterfox/comments/qcxfb7/two_options_what_to_do_if_your_cpu_doesnt_support/
Works on Intel with SSE4.1/4.2, do not on AMD with SSE4a.

**Comment by adeii** [comment]
@K4sum1 good news.
In nightly version 125.0a1 problem seems to be solved. With your patches, without rebranding, FF 32bit runs on Win 7. 
Have a try:
https://github.com/adeii/supermium-portable/releases/download/F123/firefox125x32-win7.7z

New bug: After normal browser's exit, crash reporter window appears. Next try will be FF 64bit.

**Comment by the-r3dacted** [comment]
> New bug: After normal browser's exit, crash reporter window appears. Next try will be FF 64bit.

That is the issue I encountered, it worked fine but crashed on exit if I faked version to 123.0a1, but if I set version to release it just crashes. I did figure it out though and forgot to close this.

**Comment by adeii** [comment]
Update: Some patch for 123+ still missing. 
FF 125.0.a1 opens, open YouTube video, start playing and force close whole browser after 10+ sec on Win 7 x64. Both 32bit and 64bit version of FF. No problem on Win 8 x64. _Exited "FIREFOX.EXE" (process 0x150C) with code 0 (0x0)._

https://github.com/adeii/supermium-portable/releases/download/F123/firefox125x64-win8.zip
Browser exits is normal, without crash. Memory comsuming for 1 YT tab is less than 0.5 GB, so no RAM problem.

Dependency Walker profiling shows missing api-ms-win-core-memory-l1-1-5.dll, api-ms-win-core-localization-l1-2-1.dll, api-ms-win-core-fibers-l1-1-1.dll and combase.dll;
Mozglue/xul.dll asks for unknown points like GetSystemTimePreciseAsFileTime, QueryInterruptTime, VirtualAlloc2, SetThreadDescription, GetCurrentThreadStackLimits, LdrResolveDelayLoadedAPI.

**Comment by the-r3dacted** [comment]
Must be something in 124 or 125. Not looking forward to having to do another bisect.

![ScreenShot_20240308120628](https://github.com/Eclipse-Community/r3dfox/assets/77039240/ea06cf6b-6325-46b7-aa84-388d25177968)

**Comment by adeii** [comment]
Sorry for bother you few times. This could be problem with previous 123 build - DirectX 11.
After crash of portable build, log has this:

Closing Firefox
Crash Annotation GraphicsCriticalError: |[G0][GFX1]: DoesD3D11TextureSharingWork_GetSharedTextureFailure (t=8.19)
[GFX1]: DoesD3D11TextureSharingWork_GetSharedTextureFailure
Crash Annotation GraphicsCriticalError: |[G0][GFX1]: DoesD3D11TextureSharingWork_GetSharedTextureFailure (t=8.19)
|[G1][GFX1-]: DoesRecreatingCreateTexture2DFail (t=8.19) [GFX1-]: DoesRecreatingCreateTexture2DFail
Crash Annotation GraphicsCriticalError: |[G0][GFX1]: DoesD3D11TextureSharingWork_GetSharedTextureFailure (t=8.19)
|[G1][GFX1-]: DoesRecreatingCreateTexture2DFail (t=8.19) |[G2][GFX1]: DoesD3D11TextureSharingWork_GetSharedTextureFailure (t=8.59) 
[GFX1]: DoesD3D11TextureSharingWork_GetSharedTextureFailure

https://bugzilla.mozilla.org/attachment.cgi?id=8589654&action=diff
Various flags from about:config about D3D11 and WebGPU are not helpful.
