### ISSUE TITLE
R3dfox 130 --> no settings page

### ISSUE THREAD

**Issue by ahahahaah** [Eclipse-Community/r3dfox-old#180]
hello,
i've just downladed and tryed r3dfox 64bits portable for my windows 7 pro pc
when i clic the "settings" choice in the menu it doesnt open the settings page.
Do you have the same issue?
thanks

**Comment by the-r3dacted** [comment]
It just works on my end in all my VMs. What happens if you go to about:preferences directly?

**Comment by quroe** [comment]
It works fine on windows8.1 x64.

**Comment by ahahahaah** [comment]
when i type about:preferences or about:config nothing happens
in fact i couldn't have nothing work except the main window.

i have noticed that the Windows7 taskbar displays 2 button programs with the r3dfox icon.
when i close r3dfox then one r3dfox button icon disappears from the windows7 taskbar but it still remains an other r3dfox button.
When i right-clic on it and choose the option r3dfox, i have a window from win7 that asks me if i want to launch r3dfox, and if i choose yes then r3dfox opens and all becomes normal (i can open settings page etc...).

it is weird that when i launch r3dfox there are 2 r3dfox buttons  in the windows taskbar, and if i close r3dfox then one of the r3dfox buttons of the taskbar remains, if i right-clic on it to close it then it finally closed.

**Comment by the-r3dacted** [comment]
Something is majorly broken here and I have no idea what or how.

**Comment by krystian3w** [comment]
On "my" Windows 7 with the portable version I also see 2 icons per seconds, but I almost immediately have constant access to the profile and the icon is no longer duplicated after the second launch.

**Comment by the-r3dacted** [comment]
I guess it opens a second window while initializing, and something breaks during this process causing it to also not close the window.

**Comment by ahahahaah** [comment]
i was testing it with sandboxie, outside the sandbox all is normal but i have an avast alert
![image](https://github.com/user-attachments/assets/e98dc9ed-3ebd-49be-8ba2-fca111e79262)
it says that r3dfox.exe tries to modify or delete the file cookies.sqlite which is in the desktop folder (that is protected)

**Comment by the-r3dacted** [comment]
That's the issue, if it can't modify the profile, it majorly breaks the browser. Issues with third party sandboxing or security software is not something I want to dive into especially since it is unlikely to be in my control.

**Comment by ahahahaah** [comment]
yeah as i said: outside the sandbox all is normal, i mean it works without issue, i can use it normally, which is a good new.

But now i wonder why avast detects r3dfox as a malware.  It says that r3dfox.exe tries to modify or delete the file cookies.sqlite which is in the desktop folder (that is protected).

**Comment by the-r3dacted** [comment]
> But now i wonder why avast detects r3dfox as a malware. It says that r3dfox.exe tries to modify or delete the file cookies.sqlite which is in the desktop folder (that is protected).

It probably (rightfully) sees cookies.sqlite as browser data, and therefore would trigger when an unrecognized program tries to modify it. Since r3dfox is pretty small, I don't think it would be in the browser database, therefore it accessing it's own profile would cause the issue to occur.
