### ISSUE TITLE
Make default browser

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#181]
The dialog asking me for this each time the browser start doesn't work. I have to go to Preferences to use Make default.

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive password: changeme
I put the necessary dlls in the archive

**Comment by the-r3dacted** [comment]
Weird. Not sure why. Maybe upstream bug?

**Comment by Robbbert** [comment]
Just came across this bug. Using Vista 32bit. The default is "Downloads", but I want to use C:\Download .

I used Settings which shows the address of about:preferences

After selecting it the first time, a new dialog box appears asking again. After selecting again, an error appears "The Windows file-dialog could not be opened. No file or folder could be selected."

My choice never gets accepted.

I looked in about:config but was unable to locate this setting, so I'm stuck.

**Comment by the-r3dacted** [comment]
The dialog works for me so idk. Maybe corrupted profile?
![image](https://github.com/user-attachments/assets/9fdf9057-8607-43c6-b806-90efa2ad00a7)

**Comment by Robbbert** [comment]
Looks like my comment went in the wrong issue. I was referring to the fact that you can't set the download location. I can make a new issue if you prefer.

**Comment by ghost** [comment]
> Weird. Not sure why. Maybe upstream bug?

I'm using old Windows so I can't test upstream.
