### ISSUE TITLE
Disable e10s

### ISSUE THREAD

**Issue by Naytaco** [Eclipse-Community/r3dfox-old#186]
How does the browser implement single-process mode (disabling e10s multiprocess mode)?

**Comment by the-r3dacted** [comment]
Well, Firefox never removed the old method that was behind a preference, they just kept restricting the way to enable it. So I just added a preference back.

https://github.com/Eclipse-Community/r3dfox/commit/15cf1abd6136e13f38fbf9a5cc55a8b437739e78
