### ISSUE TITLE
Firefox works with sandboxie but not r3dfox

### ISSUE THREAD

**Issue by ahahahaah** [Eclipse-Community/r3dfox-old#187]
hi,
i can sandbox firefox with sandboxie but if i want to do the same with r3dfox then r3dfox doesnt work correcty.
so if i want to go internet with r3dfox and sandboxie then i can't. I have to use it outside sandboxie.

why doesn't it react as firefox?

thanks

**Comment by the-r3dacted** [comment]
My assumption is Sandboxie can recognize Firefox as being Firefox and engages some workarounds to make it work. As r3dfox identifies as something other than Firefox, this causes problems. I don't think this is something I can fix.

**Comment by ahahahaah** [comment]
ok thx

**Comment by J4CKED** [comment]
I'm using Sandboxie v5.64.3 without a problem.

**Comment by ahahahaah** [comment]
are u with windows 7?

**Comment by J4CKED** [comment]
Yes. Win 7 sp1 x64.
