### ISSUE TITLE
[Feature Request] A progress bar beneath the Urlbar?

### ISSUE THREAD

**Issue by clifford269** [Eclipse-Community/r3dfox-old#189]
Earlier good browsers had it. Is it possible in modern Firefox? https://github.com/luben/load-progress-bar does it but within the page.

**Comment by the-r3dacted** [comment]
This would be really cool, but I'm not sure how to do it. Are there any themes or modifications other than a WebExtension that add one?

**Comment by clifford269** [comment]
There aren't, mate. I've searched all around. Used to be for 2011-ish Firefox. Perhaps you can contact people, like Travis and such?

**Comment by garry-ut99** [comment]
There is also a discussion about it on Mozilla forum: 
- [Add a loading/progress bar (desktop FF) ](https://connect.mozilla.org/t5/ideas/add-a-loading-progress-bar-desktop-ff/idi-p/30311)
- [Add a status bar and progress meter ](https://connect.mozilla.org/t5/ideas/add-a-status-bar-and-progress-meter/idi-p/32907)

**Comment by clifford269** [comment]
> zilla foru

I know, right! That is such an obvious UI enhancement. But Mozilla is the wrong place to look for it!

**Comment by the-r3dacted** [comment]
huh?
