### ISSUE TITLE
Should I apply this user.js?

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#192]
It is said to deliver the maximum performance. I found it on Reddit. The website is in Vietnamese, but fortunately most browsers have out of the box support for whole page translation to English.

https://github.com/FirefoxUniverse/FirefoxTweaksVN

What concerned me most is if I would break compatibility with websites. I care about both performance and compatibility.

**Comment by the-r3dacted** [comment]
I've been meaning to look into this, but I realize this isn't an issue with my browser. idk if it will be good or not. The GitHub repo seems to be a maze so idk where to even find the changes.

**Comment by the-r3dacted** [comment]
I just spotted user.js right when I was going to close the tab wtf

**Comment by the-r3dacted** [comment]
I don't think anything would cause issues. I think I might add some of the changes to the next r3dfox release, thanks.
