### ISSUE TITLE
r3dfox has stop working on windows vista VM

### ISSUE THREAD

**Issue by ugohohcohxihxihdig** [Eclipse-Community/r3dfox-old#194]
hello I am having issue with r3dfox because when I try to launch it after installing it on Windows Vista VM it says "r3dfox has stop working" and when i click on it only says that and does not open any solution to that thanks?

(vm = VMware 17)

**Comment by ugohohcohxihxihdig** [comment]
edit it says that xul.dll is a fault?

**Comment by youself64github** [comment]
Please make sure that you installed Platform Update, Platform Update Supplement, and SHA-2 Update on Windows Vista (Must have SP2 installed not SP1 or RTM). I installed these updates and r3dfox would run fine.
