### ISSUE TITLE
Whole browser crashes when visiting a Badoo link on 131.0.3

### ISSUE THREAD

**Issue by garry-ut99** [Eclipse-Community/r3dfox-old#196]
> https://github.com/Eclipse-Community/r3dfox/issues/195#issuecomment-2435492641 : However x86 on Vista x86 crashes after a few seconds.

Another crash on another site: whole browser crashes on a popular dating site Badoo, when visiting a link to people's profile, for example: `https://am1.badoo.com/en/people-nearby/0zAhMACTc4VGk0ODkxOQjkOhxqBBBBBCD-P6ZZ5nbll1MOfM7fR9QZ7yTUyb83pb8B20vYfDjMxA` , to reproduce the crash, it's required to be logged-in. I am on  Windows 7 SP1 64bit.

![rec](https://github.com/user-attachments/assets/ec5203a5-9251-4955-8670-86c46d16ddb5)

**Comment by the-r3dacted** [comment]
I'm going to combine this issue with https://github.com/Eclipse-Community/r3dfox/issues/197 as they seem to be the same crash. If I fix Speedtest and this still occurs I'll reopen.
