### ISSUE TITLE
r3dfox 131.0.3 crashes when running speedtest.net test.

### ISSUE THREAD

**Issue by EDSln** [Eclipse-Community/r3dfox-old#197]
It crashes both x32 and x64, I checked on a clean profile, it crashes the same way.

**Comment by the-r3dacted** [comment]
This looks to be a missing function somewhere as it runs fine on 8.1. Not entirely sure how to trace it outside of bisecting, but I'll see if Dependency Walker gives me anything.

**Comment by DoctorVovhu** [comment]
K4sum1, it doesn't crash with my old profile. With a clean profile it crashes.
![screen-8134945054](https://github.com/user-attachments/assets/c697cf1b-8174-434b-acb7-5a51ed0b8af9)

**Comment by the-r3dacted** [comment]
Ok, so geolocation in 131 was changed to depend on api-ms-win-core-winrt-string-l1-1-0.dll which is not in 7, therefore it causes a crash. I'll see if I can find the breaking change.

**Comment by the-r3dacted** [comment]
I think it might be the series of commits from Bug 1900225, I'll start digging into them.

**Comment by the-r3dacted** [comment]
Made a fix, will ship in 131.0.3 (non-rc)

**Comment by the-r3dacted** [comment]
Fixed in 131.0.3 non-rc
