### ISSUE TITLE
Crash on geolocalization site request

### ISSUE THREAD

**Issue by JonnyThree** [Eclipse-Community/r3dfox-old#198]
Hello i have found a bug in latest version 131.0.3. When a website request user confirmation on geolocalization, browser crash. If i switch "geo.enabled" on "false", the crash doesnt occour.
I have also Italian language pack installed on r3dfox, if this is relevant, i don't know

**Comment by the-r3dacted** [comment]
Same issue as https://github.com/Eclipse-Community/r3dfox/issues/197
