### ISSUE TITLE
Nuke maintenance service

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#2]
The maintenance service is useless and is bloat. I would like to remove it from the installer, or better yet the browser source entirely.

**Comment by mrrpmrreeoow** [comment]
> The maintenance service is useless and is bloat. I would like to remove it from the installer, or better yet the browser source entirely.

I dont think removing maintenance service is a good idea.
It allows people on non-admin accounts to update the browser.
Yes, there are currently no update servers, but I hope they will be in the future when Vyvfox officially releases.
I would hate using/installing a web browser that cannot update itself on non-administrator accounts, or even worse, not update at all.

**Comment by the-r3dacted** [comment]
> I dont think removing maintenance service is a good idea. It allows people on non-admin accounts to update the browser. Yes, there are currently no update servers, but I hope they will be in the future when Vyvfox officially releases. I would hate using/installing a web browser that cannot update itself on non-administrator accounts, or even worse, not update at all.

I've never had it do anything for me. Also how could it update the browser? It's in Program Files. It would need admin. Also if you're using an non-admin account isn't there a fallback install in AppData anyways?

**Comment by mrrpmrreeoow** [comment]
> > I dont think removing maintenance service is a good idea. It allows people on non-admin accounts to update the browser. Yes, there are currently no update servers, but I hope they will be in the future when Vyvfox officially releases. I would hate using/installing a web browser that cannot update itself on non-administrator accounts, or even worse, not update at all.
> 
> I've never had it do anything for me. Also how could it update the browser? It's in Program Files. It would need admin. Also if you're using an non-admin account isn't there a fallback install in AppData anyways?

https://support.mozilla.org/en-US/kb/what-mozilla-maintenance-service
https://wiki.mozilla.org/Windows_Service_Silent_Update

**Comment by thecatontheceiling** [comment]
> > I dont think removing maintenance service is a good idea. It allows people on non-admin accounts to update the browser. Yes, there are currently no update servers, but I hope they will be in the future when Vyvfox officially releases. I would hate using/installing a web browser that cannot update itself on non-administrator accounts, or even worse, not update at all.
> 
> I've never had it do anything for me. Also how could it update the browser? It's in Program Files. It would need admin. Also if you're using an non-admin account isn't there a fallback install in AppData anyways?

kasumi are you retarded

**Comment by the-r3dacted** [comment]
> kasumi are you retarded

they call me r3tard

**Comment by MiholaL** [comment]
This is even worse than twitter's repository... Why the hell would you want to remove a service that is responsible for updating the browser?

**Comment by the-r3dacted** [comment]
Disabled via mozconfig for 122 release, might further remove from installer code.
