### ISSUE TITLE
Get Aero working correctly

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#20]
Edit 2: This first comment is mostly obsolete, the real issues are below. I will edit them in below to make it easier to find.

The top of tabs seem to meet the top of the screen or even get cut off maximized. Looks weird, will need to investigate.

![ScreenShot_20240313220753](https://github.com/Eclipse-Community/r3dfox/assets/77039240/f71c3ead-09a8-4ca0-aa82-a26e4e0e09ea)

Need to force inactive tab text to be black under 8.1. It seems to be black under 7 which helps with Aero. It's white on 8.1 which can be an issue with some Aero themes.

(See above or below)

Also not sure if 8.1 only or if I just didn't notice in test VM, but inactive window tabs are faded and it looks weird and harder to distinguish.

![ScreenShot_20240313222037](https://github.com/Eclipse-Community/r3dfox/assets/77039240/66bb8317-bea8-4e0f-a6b0-17ee59640b31)

Edit: I realized it might be a good idea to offer the release in its current state. It otherwise works fine on 7 at least in my limited testing. It just has this issue. https://files.catbox.moe/lqhhv2.7z

I have gotten 123 almost there, but I want to finally get Aero working before I make a new release. It's mostly there, it's just the main component of the tab bar is covered by the theme. I'm not sure what could cause this or how to figure it out. Classic theme is even worse because the buttons are hidden behind what draws the theme color and can't be used.

I'm also fairly certain my reverts to get it this far need cleaning up, but I have no idea what I could trim or improve. They might just need to be full on replaced with more compatible code. I have no idea.

What Windows 7 with Aero looks like:
![ScreenShot_20240308164817](https://github.com/Eclipse-Community/r3dfox/assets/77039240/3d5d1a97-db39-4f93-b36c-0aaa7922c0d8)

What Windows 7 with classic theme looks like:
![ScreenShot_20240308170748](https://github.com/Eclipse-Community/r3dfox/assets/77039240/d67451ec-d285-401f-9d83-ff04732afeaf)

@Alex313031 since you maintain Mercury and are a contributor, I really hope you can help with this please.

@1280px I spotted that you helped with the theme in MyPal68. I really hope you can help here too please.

**Comment by the-r3dacted** [comment]
This was suggested to me. I have no idea what it entails or how easy or hard it would be, but I'd rather not do it to keep r3dfox as a basic this is just normal Firefox but 7 compatible fork point. 

Just keep the GUI from 115 but update the engine.

I do kinda like the idea because it would make theming easier and make an alternative objective easier to accomplish. https://github.com/Eclipse-Community/r3dfox/issues/4

Although if I could just use an old GUI, I would kinda prefer to use the GUI from 70 or so. Including things like the old about:config page and such. However that would be for an alternative project as that wouldn't make it the basic fork point like i imagine this could be.

**Comment by the-r3dacted** [comment]
Quick bodge. Currently Classic theme has no native colors. Basic is just a basic semi-matching flat color. Was begged to release, so making release build early.

https://github.com/Eclipse-Community/r3dfox/commit/2f17cf05bf49f00934be3773447e80657c11f3f7

I want to deep dive into the code and properly fix it so this isn't needed, but will have to wait.

Thanks to @florinsdistortedvision for the help in making this (it was 95% him)

**Comment by the-r3dacted** [comment]
The top of tabs seem to meet the top of the screen or even get cut off in full screen. Looks weird, will need to investigate.

**Comment by the-r3dacted** [comment]
Need to force inactive tab text to be black under 8.1. It seems to be black under 7 which helps with Aero. It's white on 8.1 which can be an issue with some Aero themes.

Also not sure if 8.1 only or if I just didn't notice in test VM, but inactive window tabs are faded and it looks weird and harder to distinguish.

**Comment by wealstarr** [comment]
I'm using windows 10 theme on 8.1 and the missing title bar in version 123 creates a visual artifact, dark tabs with white background. It also borrows caption buttons from the Windows theme and does not uses it's own which creates another visual artifact. This doesn't have anything to do with theme itself, without the r3dfox title bar and caption buttons artifacts will be consistent no matter it's stock theme or 3rd party theme or Windows 10 theme.

I understand  you don't want to change the user interface from version 123, in that case will it be possible to compile 2 binaries, one with title bar and caption bar like in version 122 and one as in version 123 ?

Kind regards

**Comment by unter-officer** [comment]
I support the request **wealstarr**.
Compile 2 binaries, one with title bar and caption bar like in version 122 and one as in version 123.

**Comment by rovickti** [comment]
K4sum1:
> What Windows 7 with Aero looks like:

I see a similar thing running Firefox 123 with VxKex, when running classic. Firefox 123 when maximised doesn't fully take up all the available space. Firefox ESR or r3dfox 123.0.2 under classic takes up space. 

Maybe it would help to also ask the [VxKex](https://github.com/vxiiduu/VxKex/issues) people how their support for Firefox 123 is going under both classic and aero?

---

I notice that the interface text e.g. in the address bar, is slightly smaller than Firefox ESR. 

With the system theme enabled the colors (e.g. blue from using a classic theme) don't show in the r3dfox or VxKex Firefox 123 menu bar / tabs. The color is light instead of the theme colors. I take these are new Firefox things.

**Comment by the-r3dacted** [comment]
I'll get around to making r3dfox versions of 117-121. The entire idea of this is to make these older versions to make pinpointing issues easier. I want to figure out where backporting the theme broke, and figure out what visual changes happened in said version, so I know what to do for later versions. When I do this, this should fix the issues caused by the bodge. If there are still visual issues, just use regular Firefox with VxKex, or if 8, Firefox + winvertroll (https://board.eclipse.cx/viewtopic.php?t=652).

> Maybe it would help to also ask the [VxKex](https://github.com/vxiiduu/VxKex/issues) people how their support for Firefox 123 is going under both classic and aero?

It's like r3dfox 122, it just uses the modern theming because it's from before I backported Aero. It just has enough functions to get it running on 7 without any major issues.

> I notice that the interface text e.g. in the address bar, is slightly smaller than Firefox ESR.

I assume it's from the bodge since stock Firefox 125 doesn't have it. Unless they undid the change for 125 idk. I'll get around to that when I fix the theme.

> With the system theme enabled the colors (e.g. blue from using a classic theme) don't show in the r3dfox or VxKex Firefox 123 menu bar / tabs. The color is light instead of the theme colors. I take these are new Firefox things.

r3dfox issue is because of the bodge, I need to fix that. Firefox 123 just recreates the 10 title bar in CSS.

**Comment by unter-officer** [comment]
Since the “Aero” topic was closed, I’ll write a request here.
Compile please 2 binaries, one without Aero and with the original window interface as it was in version 122, and one with Aero.

**Comment by the-r3dacted** [comment]
> Since the “Aero” topic was closed, I’ll write a request here. Compile please 2 binaries, one without Aero and with the original window interface as it was in version 122, and one with Aero.

If this is still an issue when I replace the bodge with a proper Aero UI, then I'll do that.

**Comment by the-r3dacted** [comment]
Aero should be on par with 115 in 124.0.2-aero.

https://github.com/Eclipse-Community/r3dfox/releases/tag/124.0.2-aero

Post any future issues in https://github.com/Eclipse-Community/r3dfox/issues/36

**Comment by the-r3dacted** [comment]
If anyone is still interested, I realized there already is a method to get the Windows 10 UI on r3dfox on any Windows version.

Go to about:config and set widget.ev-native-controls-patch.override-win-version to 10

![r3dfox win 10 ui on 7](https://github.com/user-attachments/assets/db706ccf-73fe-4b1b-a227-4313b9e317d0)
