### ISSUE TITLE
Pick a better name, please, and colour

### ISSUE THREAD

**Issue by clifford269** [Eclipse-Community/r3dfox-old#200]
Even 'redfox' would've suited. Aero blue is the standard choice to be picked though, given the Windows versions targetted. Also having 'Eclipse' written in the windows is a bit unnecessary and cluttersome.

**Comment by the-r3dacted** [comment]
> Even 'redfox' would've suited.

There's lore
https://github.com/Eclipse-Community/r3dfox/issues/33

> Aero blue is the standard choice to be picked though

I guess, but stock Firefox is already blue.

> Also having 'Eclipse' written in the windows is a bit unnecessary and cluttersome.

I like it

**Comment by clifford269** [comment]
You're an arrogant little fool, you know that? Soon superfox is gonna come in with sensible UI, names and non-anime profile pictures and this shitshow will even stop getting the little usage it got. Oblivion it is, for you, anime kid.

**Comment by the-r3dacted** [comment]
> Soon superfox is gonna come in with sensible UI

Bruh your UI looks like this
![Untitled](https://github.com/user-attachments/assets/5e7831fc-0853-4b71-8674-62a5f345aa5d)
You have no room to talk

Also 128 ESR fork with closed source wrapper dlls that could contain anything is going to kill fork of latest, now 132 Firefox? I don't think so. With how long I've been hearing about it, I don't think it's ever going to be coming out.
