### ISSUE TITLE
Luminafox, Snowfox, Superfox

### ISSUE THREAD

**Issue by trimechee** [Eclipse-Community/r3dfox-old#201]
Hi Mr @K4sum1 , you kindly informed me weeks ago about Luminax a browser inspired by R3dfox , but I discover today with sadness that the project is discontinued , but I see an announcement that Luminafox is replaced by a new browser: Snowfox .

maybe this new project will help to lighten the workload, bug fixing, maintenance.....but what is mysterious there are several versions of Snowfox and we don't know which version is the official one :

Snowfox
https://github.com/0h7z/Snowfox
https://github.com/Heptazhou/Snowfox
https://0h7z.com/en/snowfox/
https://github.com/winrevive/snowfox

alos, the developer of famous supermium browser made new browser based on firefox :

superfox
https://github.com/users/win32ss/projects/2

also i find rare software to update windows 7 os with new updates but sadly, it is only 64 bits only :

https://github.com/winrevive/win7-sp2
https://sp2.winrevive.xyz/

**Comment by the-r3dacted** [comment]
When did I say this was discontinued?

**Comment by trimechee** [comment]
@K4sum1 :  I didn't say that you told me that luminafox is discontinued, I said you informed me about the existence of luminafox which apparently is inspired by your web browser, and today I check if luminafox has been updated and I see the announcement that luminafox is no more updated and replaced by the new snowfox browser : 

https://github.com/winrevive/luminafox

**Comment by the-r3dacted** [comment]
Oh, I misinterpreted what you said, and then I kinda just skimmed the rest of this from there before posting the comment so I didn't catch that.

Also from what I saw you linked both a different Snowfox browser and the Luminafox successor Snowfox.

**Comment by trimechee** [comment]
yes, I myself i am lost what is the official link of the successor of Luminafox, normally, since Luminafox is based on part of your code, the new Snowfox must take your explicit prior agreement before making this new fork....
