### ISSUE TITLE
a sandbox in r3dfox?

### ISSUE THREAD

**Issue by ahahahaah** [Eclipse-Community/r3dfox-old#204]
hello
in the notes realase of redfox 132 i can see 

> Notable bugs:
> The 32 bit build is built with --disable-**sandbox**.  ... The 64 bit build is fine.
> 

is there a sandbox in the browser? 
how to enable it?
does it work as sandboxie or other sandboxes to not let viruses/scripts or hacked webpages to escape in windows and infect it?

**Comment by the-r3dacted** [comment]
Firefox started using the Chromium sandbox a while back for security I guess. This shouldn't effect Sandboxie or similar. I'm not sure how it works. All I know is that it doesn't work on Vista when using x86 build.
