### ISSUE TITLE
Unsigned icons in ESR 128.4.0

### ISSUE THREAD

**Issue by EDSln** [Eclipse-Community/r3dfox-old#206]
The ESR 128.4.0 installer creates unsigned icons on the desktop and Start menu.
![not naming](https://github.com/user-attachments/assets/49f15250-ded6-4d3f-bbf5-616ed9c26f49)
![not naming1](https://github.com/user-attachments/assets/19ed5836-e951-439f-a85c-8e7333ec828f)

**Comment by the-r3dacted** [comment]
I think I realized the mistake. I'll get that fixed, but it'll be a couple hours before I can get the builds out.

**Comment by the-r3dacted** [comment]
Fixed
https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.4.0-hotfix
