### ISSUE TITLE
my Intel celeron 2950M can't run v123.0.2 x64 SSE4.

### ISSUE THREAD

**Issue by jonm58** [Eclipse-Community/r3dfox-old#21]
v123.0.2 x64 SSE4
Windows 11 22000.2538
CPU-Z:![屏幕截图 2024-03-11 062641](https://github.com/Eclipse-Community/r3dfox/assets/73036321/99bc0a8e-d88a-4411-8575-55351639b241)
error 0xc0000142:
![image](https://github.com/Eclipse-Community/r3dfox/assets/73036321/dead5fe4-de87-48d8-b52c-73dc45dcc1fa)

**Comment by the-r3dacted** [comment]
I took a look at my mozconfig and I accidentally left some AVX2 code enabled. Will publish another build.

**Comment by the-r3dacted** [comment]
Try this
https://github.com/Eclipse-Community/r3dfox/releases/tag/123.0.2-2-beta-aero

**Comment by jonm58** [comment]
fix
