### ISSUE TITLE
Transparence & text problem 

### ISSUE THREAD

**Issue by WindowsDefen517** [Eclipse-Community/r3dfox-old#211]
Hello, i wanted to get the old transparence on r3dfox 132.0.2 and my test is white when the dark mode is enabled
![image](https://github.com/user-attachments/assets/f59bbac8-2392-43b2-b4cd-3e0906c924b4)

**Comment by the-r3dacted** [comment]
From what I can tell it looks like you're using a custom userChrome.css. These may have issues in r3dfox due to some of the color defines being changed for glass support. You'll probably need to fix that yourself.
