### ISSUE TITLE
[Suggestion] Pre-set pref "security.dialog_enable_delay" to 0

### ISSUE THREAD

**Issue by Jevil7452** [Eclipse-Community/r3dfox-old#212]
In theory, it's supposed to be some security feature
In practice, it's just an annoyance that makes the user wait a second before the Save button gets enabled on a download dialog. Gets tedious if you want to download a lot of files quickly.

**Comment by the-r3dacted** [comment]
At what point does the old save dialog appear? I'm pretty sure it's been gone for a while now.

**Comment by Jevil7452** [comment]
I believe you can set it to ask you for confirmation on download. Eitherways, I'm talking about this dialog: ![61108.png](https://github.com/user-attachments/assets/9433e554-fbb7-4381-9b87-7736f9d55384)

**Comment by the-r3dacted** [comment]
I'll just do it now in the code because I will forget if I wait until I work on r3dfox next

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/commit/37f0aa655617612dd22d5c78c55f8498d8e7171e
