### ISSUE TITLE
r3dfox 128.4.0esr although AddIns activated they not work

### ISSUE THREAD

**Issue by informatorius** [Eclipse-Community/r3dfox-old#219]
r3dfox 128.4.0esr I added some AddIns and although activated they do not work

Windows 7 64bit latest patches

**Comment by DAPOPOBEFASTONYOAZZ** [comment]
Please specify which addons you have installed so it can be reproduced. Some addon builds may be old and may not work with newer versions.

**Comment by informatorius** [comment]
All AddOns.
Like Adguard, DarkReader, TWP, 
That is strange!

**Comment by the-r3dacted** [comment]
I use TWP in my 128.4.0 and it works fine?

**Comment by DAPOPOBEFASTONYOAZZ** [comment]
I used DarkReader on 128.4 and also use it on the current release and I am not facing any issues. Not sure what the problem is for you. You may want to check other aspects in your set up.

**Comment by informatorius** [comment]
OK, I will check by setup
