### ISSUE TITLE
Error when detecting the current location

### ISSUE THREAD

**Issue by Nvdtn19** [Eclipse-Community/r3dfox-old#221]
On some maps site like Google Maps, Bing Maps and OpenStreetMap, my current location couldn't be detected and instead it's showing an error when using the auto location detecting feature. Same thing goes in Plasmafox 133 as well. Using Windows 7 x64 and r3dfox 132. 
Official 115 ESR and Supermium does not have this error, however.
Below is some screenshot that displaying the errors --
![Screenshot 2024-11-25 at 22-10-23 Bing Maps - Directions trip planning traffic cameras   more](https://github.com/user-attachments/assets/3ccd5d1c-08a5-4330-8842-6efd317e9e69)
![openstreetmap](https://github.com/user-attachments/assets/8471f62f-4f4b-459f-b909-16f582e1298c)
![Screenshot 2024-11-25 at 21-56-08 Google Maps](https://github.com/user-attachments/assets/c5558a1a-85f1-42d4-8625-6d0c94db10c9)

**Comment by jonm58** [comment]
r3dfox doesn't have the money to buy a Google location services key

**Comment by jonm58** [comment]
@Nvdtn19 
https://github.com/Blaukovitch/Mozilla_Firefox_Windows_7
this maybe work

**Comment by jonm58** [comment]
@K4sum1 Close this issues

**Comment by Nvdtn19** [comment]
> @Nvdtn19
> https://github.com/Blaukovitch/Mozilla_Firefox_Windows_7
> this maybe work

Haven't heard of this thing. I may try later to see if it works then

**Comment by garry-ut99** [comment]
> jonm58: https://github.com/Eclipse-Community/r3dfox/issues/221#issuecomment-2498597773 : r3dfox doesn't have the money to buy a Google location services key

So after many videos not working on many popular sites due to a lack of Widevine license: https://github.com/Eclipse-Community/r3dfox/issues/215#issuecomment-2473061044 which costs too much $ for R3dfox, now the same happens with maps localization feature on many popular maps sites. Wondering what else will stop working soon in R3dfox due to a lack of $.

**Comment by jonm58** [comment]
> > jonm58: [#221 (comment)](https://github.com/Eclipse-Community/r3dfox/issues/221#issuecomment-2498597773) : r3dfox doesn't have the money to buy a Google location services key
> 
> So after many videos not working on many popular sites due to a lack of Widevine license: [#215 (comment)](https://github.com/Eclipse-Community/r3dfox/issues/215#issuecomment-2473061044) which costs too much $ for R3dfox, now the same happens with maps localization feature on many popular maps sites. Wondering what else will stop working soon in R3dfox due to a lack of $.

Are you saying open source is dead?

**Comment by garry-ut99** [comment]
No, I'm saying what I'm writing, nothing more, nothing less, which means I was just wondering, and nothing more, I was curious how many technologies in Firefox require payed licences, and how much usable (or unusable) a Firefox can be without these technologies. I didn't try to suggest disappointment of R3dfox if that's how you read my comment, rather a disappointment of reality. I do support open source definately.
