### ISSUE TITLE
Problem with about:home

### ISSUE THREAD

**Issue by marty60** [Eclipse-Community/r3dfox-old#226]
You probably can't test this unless you have an older computer but I have a Pentium 4 second hand that I use on occasion and for some reason about:home will not come in with 128esr. It will once and only if that is the startup page but even then you can't duplicate it or create a new one, it just comes up blank. Not seeing this with any of the other "about" pages 

Sometimes I have this problem on my good computer as well but usually after pressing bookmark two or three times it will render.

Tried changing settings, compatibility to Vista, new profile but nothing resolves it. Other than that it works very well, even better than 115.0 but this keeps me from using it.

**Comment by the-r3dacted** [comment]
I know that about:home issue can occur when e10s is disabled. Does that option happen to be ticked on your machine?

**Comment by marty60** [comment]
> I know that about:home issue can occur when e10s is disabled. Does that option happen to be ticked on your machine?

No in settings that option is unchecked. 

The page loads but the elements won't come in. Only on the first tab does it work sometimes but if you duplicate it or open new tabs it's blank.

**Comment by the-r3dacted** [comment]
Can you test releases and find out what is the first release to have the issue?

**Comment by marty60** [comment]
It took some time but Release v127.0rc2 is good then it breaks with Release v127.0. Went back and forth several times to make sure.

**Comment by marty60** [comment]
It took some time but Release v127.0rc2 is good then it breaks with Release v127.0. Went back and forth several times to make sure.

Most likely related to this change with Release v127.0:

Changes on top of the previous 127.0rc2 build:
GUI option to disable e10s.

**Comment by the-r3dacted** [comment]
Hmm
Do you happen to have MOZ_FORCE_DISABLE_E10S set as an environment variable?

**Comment by marty60** [comment]
> Hmm Do you happen to have MOZ_FORCE_DISABLE_E10S set as an environment variable?

Good catch. As a matter of fact I did from several years ago and completely forgot about it since Mozilla had made it useless anyway with their changes. Deleted it and now it's working.

**Comment by the-r3dacted** [comment]
Yeah, that would do it. I restored the functionality of that environment variable as well as gave a GUI option.
