### ISSUE TITLE
WebRender Software only issue

### ISSUE THREAD

**Issue by MXPHunter** [Eclipse-Community/r3dfox-old#23]
WebRender is Software only. Got no luck to turn it back. 115esr works in Hardware mode on same config.

**Comment by the-r3dacted** [comment]
What GPU do you have?

Also try setting layers.acceleration.force-enabled to true in about:config.

**Comment by MXPHunter** [comment]
GPU Eclipse-Community/r3dfox#2 Radeon RX 580 Series

tried with all possible combinations of
user_pref("gfx.canvas.remote", true);
user_pref("gfx.direct2d.force-enabled", true);
user_pref("gfx.webrender.all", true);
user_pref("gfx.webrender.enabled", true);
user_pref("gfx.webrender.enabled-no-gpu-process-with-angle-win", true);
user_pref("gfx.webrender.svg-images", true);
user_pref("layers.acceleration.disabled", false);
user_pref("layers.acceleration.force-enabled", true);
user_pref("layers.gpu-process.force-enabled", true);
user_pref("layout.css.backdrop-filter.enabled", true);
user_pref("media.hardware-video-decoding.force-enabled", true);
user_pref("media.wmf.dxva.d3d9.amd-pre-uvd4.disabled", false);
user_pref("pdfjs.enableWebGL", true);
user_pref("webgl.force-enabled", true);
user_pref("webgl.out-of-process", true);
user_pref("webgl.out-of-process.force", true);

**Comment by jonm58** [comment]
You are use Windows 7?
if is,You install Windows 7 Platform Update?

**Comment by the-r3dacted** [comment]
Can confirm is an issue comparing against 122 with similar GPU. Will try to fix.
![DSC_0011](https://github.com/Eclipse-Community/r3dfox/assets/77039240/6a9a558f-3f60-4ffd-821a-55c198587fbe)
![DSC_0013](https://github.com/Eclipse-Community/r3dfox/assets/77039240/27101b74-9bae-4504-90c3-afa42276f176)

**Comment by MXPHunter** [comment]
> You are use Windows 7? if is,You install Windows 7 Platform Update?

yes (of course) / yes (KB2670838 installed since 2014)

**Comment by the-r3dacted** [comment]
Pushed a new build, should fix this issue.

https://github.com/Eclipse-Community/r3dfox/releases/tag/123.0.2-3-beta
