### ISSUE TITLE
r3dfox doesn't open on windows vista 

### ISSUE THREAD

**Issue by argrevi** [Eclipse-Community/r3dfox-old#232]
as the title says, r3dfox does not open on windows vista, at first, it was because i didn't have a dll file, but then i installed a update that had it, and this particular issue was resolved, but the program still crashes when i try to open it.

**Comment by youself64github** [comment]
Please ensure that Service Pack 2, Platform Update, Platform Update Supplement, and SHA-2 Update are installed on Windows Vista. This helps r3dfox to run in Windows Vista.

**Comment by argrevi** [comment]
thanks! it worked
