### ISSUE TITLE
Suggestion: Option to identify r3dfox user agent as normal Firefox

### ISSUE THREAD

**Issue by rovickti** [Eclipse-Community/r3dfox-old#27]
Option to identify r3dfox user agent as normal Firefox

Some websites don't support less common or older browsers. These websites usually are more complex and have some sort of application or service. These websites will likely be flakey or not support r3dfox.

One example is Twitch. Twitch only supports the last 2 versions of a browser.Twitch doesn't support Firefox ESR 115 for logging into it's accounts or registering. Twitch probably doesn't support r3dfox even now. 

https://help.twitch.tv/s/article/supported-browsers?language=en_US#firefox
> The Twitch website, twitch.tv and supporting sites, officially support the latest 2 versions of Mozilla Firefox.

Firefox on mobile has a addons/option to report as Chrome, as google discriminates by browser and serves result pages with more features for Chrome.

* https://news.ycombinator.com/item?id=20488623
* https://addons.mozilla.org/en-GB/firefox/addon/google-search-fixer/

Google has even chosen technology stacks on Youtube, like deprecated version of Polymer, for long periods (1+ years) knowing full well that Firefox would have a massive performance hit while Chrome wouldn't. An organisation without corporate bias simply wouldn't roll out such technology in production versions of websites. Google aren't following "[don't be evil](https://en.wikipedia.org/wiki/Don%27t_be_evil)" these days, in fact Google were taken to court by their own employees for breaching "don't be evil". If Google were not being evil, the human race would be best served with them also help develop Firefox under a copyleft license, and ditching Chrome. Chrome just exists for corporate greed these days.:
* https://wccftech.com/mozilla-executive-claims-that-youtube-is-five-times-faster-on-chrome-compared-to-edge-and-firefox/
* https://en.wikipedia.org/wiki/Antitrust_cases_against_Google_by_the_European_Union

Given the way for-profit companies behave, it will be useful to have the option to a report user-agent as normal Firefox going forward, even if it immediately doesn't help with any website right now.

**Comment by the-r3dacted** [comment]
I might just do the Waterfox approach of just identifying as Firefox. Sure it doesn't let me do cool stuff like eBoard2 being able to identify r3dfox, but it would solve a bunch of stuff. Maybe I could bring back general.useragent.override.(website url) though.

**Comment by the-r3dacted** [comment]
So I made a mistake in 124.0.2 and instead of identifying as Firefox instead of r3dfox, it just identifies as r3dfox. I will have to do some more prodding I guess.

**Comment by the-r3dacted** [comment]
Fixed in newest release of 124.0.2, it just identifies as Firefox only now.
