### ISSUE TITLE
Suggestion: 1. Microsoft's built-in Bing search being selected by default, possibly remove it 2. replace it with Wikipedia:criticism of Microsoft

### ISSUE THREAD

**Issue by rovickti** [Eclipse-Community/r3dfox-old#28]
Search engine defaults are huge for big companies to keep on making money to satisfy corporate greed:

* https://en.wikipedia.org/wiki/Criticism_of_Microsoft
* https://en.wikipedia.org/wiki/United_States_v._Microsoft_Corp
* https://en.wikipedia.org/wiki/Microsoft_litigation
* https://en.wikipedia.org/wiki/Antitrust_cases_against_Google_by_the_European_Union

Google, who have been less evil than Microsoft with their "[don't be evil](https://en.wikipedia.org/wiki/Don%27t_be_evil)" slogan although Google are [becoming more evil](https://en.wikipedia.org/wiki/Don%27t_be_evil#Lawsuit), have paid billions to be the default  search engine for Firefox. Microsoft, for it's part, has constantly tried to buy it's way as Firefoxes default:

* https://www.computerworld.com/article/2471834/how-much-does-google-fear-microsoft-s-bing--almost--1-billion-worth--as-counted-by-the-fi.html
* https://www.omgubuntu.co.uk/2023/05/microsoft-wants-firefox-to-ditch-google-switch-to-bing

----

**Suggestion: Don't have Bing search option enabled by default, possibly remove it**

Given Microsoft's [treatment](https://github.com/Eclipse-Community/r3dfox/issues/26) of Windows 7, there should be no need to have Bing search enabled by default given it is inferior to Google, and both are less user-centric and private than duckduckgo.

**Suggestion: Replace the space taken up by the search with a line of links to Wikipedia, a separator and some links to articles. The Wikipedia links could have the Wikipedia icon before the text.**

Example

"Wikipedia: [Criticism of Microsoft](https://en.wikipedia.org/wiki/Criticism_of_Microsoft) , "[Embrace, Extend, Extinguish](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish)" , [Anti-trust](https://en.wikipedia.org/wiki/Microsoft_litigation) | [War on Open source](https://www.zdnet.com/article/ex-windows-chief-heres-why-microsoft-waged-war-on-open-source/) , [Windows 7 profits](https://www.theguardian.com/technology/2009/oct/21/windows-7-launch)"

**Comment by the-r3dacted** [comment]
I don't want to deviate too far from stock just yet. Maybe in the future I will split this into two projects, one as a basic fork point and have r3dfox as the modified browser. In which case I'll likely remove Bing and have DDG as default.
