### ISSUE TITLE
R3dfox needs KB3080149, while Firefox ESR 115 didn't

### ISSUE THREAD

**Issue by rovickti** [Eclipse-Community/r3dfox-old#29]
Error: 
> The procedure entry point EventSetInformation could not be located in the dynamic link library ADVAPI32.dll

Followed by:
> could not load XPCOM

This occurred twice while installing R3edfox 123.02. It also occurred at startup once installed.

Using VxKek fixed the error, on the installer and the browser. This implies there's an API functionality that's used only in later Windows versions, or just uncommon in older programs. The newer functionality could be imported from VxKek. I haven't encountered this error before.

Searching gave this:
* https://answers.microsoft.com/en-us/msoffice/forum/all/advapi32dll-cannot-open-only-microsoft-word/2d19ccee-7507-484a-8b2d-5ea17276a0e8#LastReply

Installing **Windows6.1-KB3080149-x64.msu** as suggested fixed it.

https://support.microsoft.com/en-us/topic/update-for-customer-experience-and-diagnostic-telemetry-0b4f29c3-8361-b748-f862-7ecedbc57cbf

> The Diagnostic and Telemetry service collects diagnostics information about functional issues on Windows systems that participate in the Windows Customer Experience Improvement Program (CEIP). 

Why would Firefox be using so much telemetry, or is the error due to something else..

**Comment by the-r3dacted** [comment]
advapi32 should not be an issue. My Windows 7 seems to have EventSetInformation even though it doesn't have KB3080149. I tried Vista Extended Kernel which doesn't have EventSetInformation and it's fine too. I could also test 7 SP0, but that is on hardware and I'm feeling lazy. (for testing and making sure AVX code doesn't try to run on SP0)

I did go through a few updates, and I think KB4474419 might add it. It has a bunch of advapi32 references and is kinda necessary these days.

**Comment by rovickti** [comment]
Weird. This is on Win 7 SP1. I also added Windows6.1-KB3102810-x64.msu while trying to fix it, but it didn't help. Other than that it was adding Windows6.1-KB3080149-x64.msu that fixed it. If this is a stock Windows 7 API call, I wonder why VxKex fixed it.
