### ISSUE TITLE
Fully rebrand browser

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#3]
Edit 2: For icons I think only installer icon remains, which I have no idea how to change. There are some textual references related to Mozilla left still.

Edit: So far these are the only things remaining; installer icon, document/html icon, and pdf icon. Some things like msix assets and macOS icons aren't changed, however there is going to be no official msix or macOS r3dfox, so no need to bother.

Installer icon I can replace, but I have no idea how. There is a setup.ico which seems to be the setup icon, but replacing it does nothing. I have no idea where else the installer icon could come from, and I've searched the entire repo for it. I can't find it.

The other icons I need to get replacements for.

**Comment by Marek33** [comment]
It's great, to see a Firefox fork, with the latest version; however, since your browser leaks this, can you keep the original logo, or somehow disable that feature? https://thehackerblog.com/dirty-browser-enumeration-tricks-using-chrome-and-about-to-detect-firefox-plugins/

**Comment by the-r3dacted** [comment]
> since your browser leaks this, can you keep the original logo, or somehow disable that feature?

So I could delete the image or even about:logo entirely, but that would look weird and be a fingerprint itself. It's pretty easy to tell if a browser is Firefox even with faked useragent, and if that gets detected, but about:logo is gone, that is as much of a fingerprint as having your own logo.

The stock Firefox branding is copyrighted, so I couldn't use the stock logo. I could use the unofficial branding logo, but that would be almost as much of a fingerprint as my own logo is.

Also like the browser sends that it is r3dfox in the useragent anyways so that bypasses the entire logo thing.

**Comment by Marek33** [comment]
I think that Tor uses Firefox logo, and apparently it's very difficult to find out, if it's Tor or Firefox, but I don't know if it's true.

Right, I forgot about that. However, is it also copyrighted for a nonprofit project?

Originally, I haven't even checked the user agent, since I guessed, it would be the same, but with **privacy.resistFingerprinting**, it's the same as Firefox.

**Comment by rovickti** [comment]
To avoid getting support or information requests about Firefox itself, perhaps there could be a sentence in r3dfox > help > about, mentioning that r3dfox is based on Firefox and the Mozilla links given for: "what's new", "firefox help", "feedback", in addition to the Eclipse community links . Also fulfills any credit attribution type expectations people may have.

> Marek33:

> Right, I forgot about that. However, is it also copyrighted for a nonprofit project?

Mozilla likely have the logo trademarked to prevent hostile imitations of Firefox, in addition to a copyright license. Art doesn't need to be under the same license as code even in GPL, and Mozilla's license is even more permissive. Having said that I doubt r3dfox would get sued, if "about:logo" used Mozilla's icon purely to resist fingerprinting, but the normal r3dfox icon was used elsewhere - especially considering it was Mozilla's decision to drop support creating the need for r3dfox in the first place.

**Comment by Marek33** [comment]
> To avoid getting support or information requests about Firefox itself, perhaps there could be a sentence in r3dfox > help > about, mentioning that r3dfox is based on Firefox and the Mozilla links given for: "what's new", "firefox help", "feedback", in addition to the Eclipse community links . Also fulfills any credit attribution type expectations people may have.
> 
> Mozilla likely have the logo trademarked to prevent hostile imitations of Firefox, in addition to a copyright license. Art doesn't need to be under the same license as code even in GPL, and Mozilla's license is even more permissive. Having said that I doubt r3dfox would get sued, if "about:logo" used Mozilla's icon purely to resist fingerprinting, but the normal r3dfox icon was used elsewhere - especially considering it was Mozilla's decision to drop support creating the need for r3dfox in the first place.

Yes, that would be a great solution, thou the end decision is on **K4sum1**. However, I'm still not sure, how much **fingerprintable** that feature really is, since I haven't seen it mentioned almost anywhere else.

**Comment by the-r3dacted** [comment]
I think it's good as is idk

**Comment by the-r3dacted** [comment]
I replaced the installer icon finally a few days ago. Think it's good enough to just close this.
