### ISSUE TITLE
Request version 124 of Firefox without manipulation

### ISSUE THREAD

**Issue by TRX99** [Eclipse-Community/r3dfox-old#33]
Hello

I appreciate you for this.

I request you to download the latest version of Firefox which is currently 124 without any manipulation. The changes you give should only work on Windows 7 and 8. Do not touch its default user interface at all and do not change it because its beauty will be lost. But if it is possible, enable the ability to use userchrome.css in it because it is very useful, but if it is not possible, please do not apply your taste in it because the default mode is more beautiful. Of course, you can put the ability to disable Proton interface in it so that anyone can enable or disable it.

Also, its fox icon is not beautiful and it is better to choose a more beautiful icon for it. Even the name you chose for the browser is not interesting at all. It is better to have a special name with an uppercase English letter and no numbers. Also, add the Compact feature of tabs to Density.

Of course, you can always provide two versions for users. One is what I said and one is based on your taste.

Thank you

**Comment by adeii** [comment]
So, you need Firefox, not r3dfox. 
In that case, you need at 3 to 4 DLL files from r3dfox and 1 manipulation for firefox.exe to run on Windows 7/8.

**Comment by MXPHunter** [comment]
> So, you need Firefox, not r3dfox. In that case, you need at 3 to 4 DLL files from r3dfox and 1 manipulation for firefox.exe to run on Windows 7/8.

maybe its time to create patcher/install pack? can you provide more info?

**Comment by the-r3dacted** [comment]
> I request you to download the latest version of Firefox which is currently 124 without any manipulation. The changes you give should only work on Windows 7 and 8. Do not touch its default user interface at all and do not change it because its beauty will be lost.

What I'm doing is building up and trying to get latest Firefox looking like 115 ESR with Aero. Current release doesn't look too well, but I have been slowly working up to get there. When I get it out, it should be good.

> But if it is possible, enable the ability to use userchrome.css in it because it is very useful,

about:config set toolkit.legacyUserProfileCustomizations.stylesheets to true

> Also, its fox icon is not beautiful and it is better to choose a more beautiful icon for it. 

The icon is meant to be like a somewhat detailed but also somewhat flat fox. Representing both the detail of 7's user interface, and the flatness of modern Firefox. If you have a better logo, go ahead and suggest it.

> Even the name you chose for the browser is not interesting at all. It is better to have a special name with an uppercase English letter and no numbers.

The name is an old reference or inside joke that I find funny. If you know, you know. ~~At least it's better than Venom Browser.~~ Again if you have a better name go ahead and suggest it.

> Also, add the Compact feature of tabs to Density.

about:config set browser.compactmode.show to true

> Of course, you can always provide two versions for users. One is what I said and one is based on your taste.

If you dislike the way 115 ESR looks and want the 10 style window, you can just use normal latest Firefox with VxKex on 7 or winvertroll on 8.1.

**Comment by wealstarr** [comment]
> So, you need Firefox, not r3dfox. In that case, you need at 3 to 4 DLL files from r3dfox and 1 manipulation for firefox.exe to run on Windows 7/8.

Is there a simple guide to do this ? I remembered I read it somewhere, can't remember where. With the UI changes done to r3dfox, I think it's time to switch to firefox or maybe LibreWolf which has telemetry already disabled.

**Comment by jonm58** [comment]
> > Even the name you chose for the browser is not interesting at all. It is better to have a special name with an uppercase English letter and no numbers.
> 
> The name is an old reference or inside joke that I find funny. If you know, you know. ~At least it's better than Venom Browser.~ Again if you have a better name go ahead and suggest it.

https://github.com/Eclipse-Community/r3dfox/issues/2#issuecomment-1879718067
👀?

**Comment by the-r3dacted** [comment]
> [#2 (comment)](https://github.com/Eclipse-Community/r3dfox/issues/2#issuecomment-1879718067) 👀?

Yeah, r3tard and r3dacted came from same person, so yeah.

![r3tard](https://github.com/Eclipse-Community/r3dfox/assets/77039240/bf858821-ccc8-4fa3-8e59-26a188c9c560)

**Comment by TRX99** [comment]
> What I'm doing is building up and trying to get latest Firefox looking like 115 ESR with Aero. Current release doesn't look too well, but I have been slowly working up to get there. When I get it out, it should be good.

I use the following extension in Firefox 115.9.1esr, which has free servers, but because of many users, it only works on the Netherlands server, which I have to click several times to connect. I installed it in r3dfox and it connects, but no matter how long I wait, it cannot open the sites, but in Firefox 115.9.1esr, it opens the sites when it connects. One of my favorite sites is Youtube, which is blocked in my country.



Of course, after working with it for a day, I realized that you should not touch its user interface at all because it has a very good user interface and it is much better than proton interface.
The only thing is one is the name of the browser and one is its icon. I myself changed its icon to my taste. For example, the name of the browser can be Superfox.

**Comment by adeii** [comment]
> Is there a simple guide to do this ?
https://www.eightforums.com/threads/firefox-122-on-windows-8-1-got-it-running.80628/  (works even for ff 126.0.a1)

For Win 7 x64, you will need libraries from r3dfox with the same version:
lgpllibs.dll, mozglue.dll, xul.dll - are mandatory.
gkcodecs.dll, nss3.dll - are possible.
libEGL.dll, libGLESv2.dll - latest version of r3dfox (124.0.x) also modd graphics to enable D3D11 on Win 7/8.

**Comment by TRX99** [comment]
> about:config set toolkit.legacyUserProfileCustomizations.stylesheets to true

Which command should I use to enable Proton UI?

**Comment by wealstarr** [comment]
> > Is there a simple guide to do this ?
> > https://www.eightforums.com/threads/firefox-122-on-windows-8-1-got-it-running.80628/  (works even for ff 126.0.a1)
> 
> For Win 7 x64, you will need libraries from r3dfox with the same version: lgpllibs.dll, mozglue.dll, xul.dll - are mandatory. gkcodecs.dll, nss3.dll - are possible. libEGL.dll, libGLESv2.dll - latest version of r3dfox (124.0.x) also modd graphics to enable D3D11 on Win 7/8.

Many thanks adeii. Seems like hassle, I'm keeping an eye on your repo for portable browsers. Right now on r3dfox 122, will see if the dev makes build available without doing anything to the UI in the future, if not, will probably grab of your builds.

Thank you for all the work, your help is highly appreciated.

PS why is there no issues section on your portable browser repo ?

**Comment by the-r3dacted** [comment]
> Which command should I use to enable Proton UI?

It's not in the browser. whatever command your userChrome.css uses I guess.

**Comment by TRX99** [comment]
> > Which command should I use to enable Proton UI?
> 
> It's not in the browser. whatever command your userChrome.css uses I guess.

After hours of working with r3dfox, I came to the conclusion that this browser is even more beautiful than the original version of Firefox, and the removal of the Proton interface made it more beautiful. The fox icon is also beautiful. The only problem is the name of the browser, which could be better, you have to think about changing it yourself. I request you to just fix the bugs if there are any and do not touch its user interface in any way and just update it and make it available for download.

**Comment by the-r3dacted** [comment]
> and the removal of the Proton interface made it more beautiful.

Oh, you mean Proton and not Photon. This still uses the Proton UI. I thought you meant something like how Waterfox defaults to Photon. Why did Firefox make the name just 1 character different?

> I request you to just fix the bugs if there are any and do not touch its user interface in any way and just update it and make it available for download.

New release coming maybe today. I've gone though and made stuff native and equal to 115 ESR aside from two changes. The Aero fog is half as intense, and background items are black too on 8 so you can actually see them and read inactive tab names.

![image](https://github.com/Eclipse-Community/r3dfox/assets/77039240/9ede30df-5d0c-4d2f-ac95-5b79b0566376)
![image](https://github.com/Eclipse-Community/r3dfox/assets/77039240/542e6748-27ea-4946-968f-d0dea3b1778a)

Screenshots are from 123, but I'm working on 124 right now. I've been porting this up from 117 to 124.

**Comment by the-r3dacted** [comment]
Here it is, made to be as close to ESR 115 style as possible. I will not make a 10 titlebar release. If you wish, you can cherry pick before the style commits and build yourself.

https://github.com/Eclipse-Community/r3dfox/releases/tag/124.0.2-aero

**Comment by i486** [comment]
I'd prefer not to start a new thread for this. Could you provide the full list of about:config changes in the latest version of r3dfox compared to the latest version of Firefox? Thanks.

**Comment by the-r3dacted** [comment]
@i486 Here are all the commits that changed about:config settings.
https://github.com/Eclipse-Community/r3dfox/commit/353e43dfc824b220cd107cd3ade17958c1f578d4
https://github.com/Eclipse-Community/r3dfox/commit/8bf45cc68d1e7cb880f06d6aa6acc2830db6f35c
https://github.com/Eclipse-Community/r3dfox/commit/7ccdc7967b5963259c93a6099bed005517b55875
https://github.com/Eclipse-Community/r3dfox/commit/08bea0938325584c9909ccd22e55684bdfc37e4e
https://github.com/Eclipse-Community/r3dfox/commit/a07c9524ba58a2844c55ea17a02e7e16a184d2a2

**Comment by i486** [comment]
Here's a user.js file that reverts redf0x's default about:config preferences based on the commit links kindly provided by @K4sum1 above.

Why use this?

If you notice any differences or issues that persist even after creating a new profile, there's a possibility that r3dfox's default about:config preferences are the cause. By placing this user.js in your profile folder, your settings will closely match Firefox's defaults. If the issue is resolved after enabling this user.js, Congratulations! You've identified that the issue was caused by one or some of the default r3dfox preferences.

Alternatively, perhaps you simply prefer the Firefox default experience! 😄

Note: I think it's highly unlikely for issues to occurred by redf0x's configs as most preferences are related to telemetry, relay, pocket, sponsors, etc. 

[user.js.zip](https://github.com/Eclipse-Community/r3dfox/files/15172734/user.js.zip)

**Comment by i486** [comment]
@K4sum1 

Could you please provide again a list of commits that include all the about:config changes that are different from stock Firefox 127.0.2?

I just did a big jump from r3dfox 125.0.3 to r3dfox 127.0.2. There are some changes I don't like, and I suspect they were caused by one of the about modifications introduced in r3dfox.

**Comment by the-r3dacted** [comment]
> Could you please provide again a list of commits that include all the about:config changes that are different from stock Firefox 127.0.2?

https://github.com/Eclipse-Community/r3dfox/commit/2f5455ebc95e0ed4543ce03d472b3c9675815fb3

~~You can also just about:confignew~~

**Comment by i486** [comment]
> > Could you please provide again a list of commits that include all the about:config changes that are different from stock Firefox 127.0.2?
> 
> [2f5455e](https://github.com/Eclipse-Community/r3dfox/commit/2f5455ebc95e0ed4543ce03d472b3c9675815fb3)
> 
> ~You can also just about:confignew~

I was actually referring to the new preferences rather than the editor. Classic about:config from nara is fine :stuck_out_tongue: 

Anyway, I think I found what I was looking for. It seems you consolidated all the r3dfox-specific preferences under a single commit called [Customized preferences](https://github.com/Eclipse-Community/r3dfox/commit/01bfb1ee451ccb2d1a72e4d03454262f5cf45c0b). This consolidation makes it much easier to keep up with the pref changes. It would be nice if you could also list any newly changed preferences in r3dfox on the Releases page in the future. Thank you.

By the way, my add-ons aren't showing descriptions, homepage, clickable author name and reviews on the selected add-on page:

![image](https://github.com/Eclipse-Community/r3dfox/assets/625325/1b181182-0b7b-48b7-aa94-b77c267345b8)

It’s most likely related to `extensions.getAddons.cache.enabled`
I’ve enabled it, so hopefully the add-on metadata will start showing up again soon.

**Comment by jonm58** [comment]
extensions.getAddons.cache.enabled use network for add-on metadata and themes photo

**Comment by the-r3dacted** [comment]
Should I enable it? I think I disabled it for privacy reasons in the past.

**Comment by i486** [comment]
> Should I enable it? I think I disabled it for privacy reasons in the past.

Yes, please enable it.

Personally, I don't care if AMO knows what extensions I've installed. According to [this](https://blog.mozilla.org/addons/how-to-opt-out-of-add-on-metadata-updates/), this data is sent once every 24 hours. Moreover, this data is already collected by AMO when we install from their store.

However, not having descriptions and author links on the add-on pages is a significant issue for me. I didn't back up my profile before updating to version 127, so if I don't get this metadata back in 24 hours, I'll have to reinstall more than 40 add-ons to retrieve these information.

Also see:
https://github.com/arkenfox/user.js/issues/615
https://github.com/BrowserWorks/Waterfox/issues/370

**Comment by the-r3dacted** [comment]
If anyone is still interested, I realized there already is a method to get the Windows 10 UI on r3dfox on any Windows version.

Go to about:config and set widget.ev-native-controls-patch.override-win-version to 10

![r3dfox win 10 ui on 7](https://github.com/user-attachments/assets/db706ccf-73fe-4b1b-a227-4313b9e317d0)

**Comment by wealstarr** [comment]
@K4sum1 thank you but even after enabling that flag r3dfox still produces visual artifacts and that red accent color never goes away even when custom themes are used. Your screenshot looks different mine.

**Comment by the-r3dacted** [comment]
> @K4sum1 thank you but even after enabling that flag r3dfox still produces visual artifacts and that red accent color never goes away even when custom themes are used. Your screenshot looks different mine.

Settings, disable r3dfox theme styles and colors

**Comment by wealstarr** [comment]
@K4sum1 Thanks for tip. Every thing's sorted except for caption buttons background

![Capture](https://github.com/user-attachments/assets/fb85d76a-36dd-43d1-be68-03eaf657cefb)

Any way to get rid of this ?

Btw, the style modifications are really awesome. Specially liked the compact toolbars and MacOS scrollbar.

I just hope, you could sort this little caveat so I could made r3dfox my permanent browser. It was until 122 after that UI broke.

**Comment by the-r3dacted** [comment]
Since this is the 10 title bar in CSS, you could probably browser toolbox it and remove the background there, and put the fix in a userChrome.css

**Comment by wealstarr** [comment]
@K4sum1 

I don't know how to write userChrome.css, I use from Wavefox. Can you help add to it what's needed to make r3dfox behaves like stock firefox ?

Also, custom themes from Addon store doesn't apply to about: pages while it does in Firefox.

**Comment by wealstarr** [comment]
https://github.com/QNetITQ/WaveFox

**Comment by the-r3dacted** [comment]
What browser or addon store theme do you use?

**Comment by wealstarr** [comment]
@K4sum1 

[This is the theme I made, signed from AMO](https://addons.mozilla.org/en-US/firefox/addon/mild_1/)

**Comment by the-r3dacted** [comment]
Where does the green and yellow theme come from?

**Comment by wealstarr** [comment]
that i just installed from about:addon recommendation

**Comment by wealstarr** [comment]
![Capture](https://github.com/user-attachments/assets/bb6686d4-0a4d-4b88-8470-ed16a0ab74f9)

**Comment by the-r3dacted** [comment]
That might be wavefox? I don't appear to have it.

![image](https://github.com/user-attachments/assets/0b384cc4-132d-4b41-b7e1-04cd33303118)

**Comment by wealstarr** [comment]
@K4sum1 

Wow!!!  How did you do it ? Please tell me. I cleaned r3dfox, installed again but it's not working on my end.

Please share your prefs.js and chrome folders

**Comment by wealstarr** [comment]
It's there with or without wavefox

**Comment by the-r3dacted** [comment]
I'm using 129.0.1 portable on my Windows 7 VM. I created a new profile and just added the pref, disabled the r3dfox theme, and enabled that theme from the store. No weird background here.

**Comment by wealstarr** [comment]
@K4sum1 could you share your prefs.js ?

**Comment by the-r3dacted** [comment]
I made a fresh profile and added the pref, I don't think this is the issue, but sure.
[prefs.zip](https://github.com/user-attachments/files/16914855/prefs.zip)

**Comment by wealstarr** [comment]
@K4sum1 

Thanks bud. Unfortunately doesn't work for me. Caption bar background is still different from rest of title bar background.

![Capture](https://github.com/user-attachments/assets/1d7144d3-3054-42f1-bade-b11072e56f4a)

**Comment by the-r3dacted** [comment]
What Windows version and theme are you using?

**Comment by wealstarr** [comment]
@K4sum1 
Windows 8.1 default white theme

**Comment by the-r3dacted** [comment]
Make a userChrome.css with this
```
        .titlebar-button {
          background-color: transparent;
          stroke: white;
        }
        .titlebar-button:hover {
          background-color: SelectedItem;
          stroke: white;
        }
```

On my end I seem to have a purple border I can't get rid of, but I don't see it on your end, so I'm assuming it's not an issue.

**Comment by wealstarr** [comment]
@K4sum1 

Thanks bud, it's the same with or without userChrome.css

I have no purple border, apart from that one anomaly of caption buttons background, everything else is fine. 

I don't think a simple on the fly solution could fix it, needs time to investigate and patch it from within the browser.

One thing I've been meaning to ask you, the MacOS scrollbar is so awesome in r3dfox, how do I get it on stock Firefox ? What Files/code do I need ?

**Comment by the-r3dacted** [comment]
> Thanks bud, it's the same with or without userChrome.css

In my rush to make a response, I forgot to add !important. I forgot you need that if used in a userChrome.css

```
        .titlebar-button {
          background-color: transparent !important;
          stroke: white !important;
        }
        .titlebar-button:hover {
          background-color: SelectedItem !important;
          stroke: white !important;
        }
```

> One thing I've been meaning to ask you, the MacOS scrollbar is so awesome in r3dfox, how do I get it on stock Firefox ? What Files/code do I need ?

I think the code already exists in Firefox, just set widget.non-native-theme.scrollbar.style to 1 for the macOS scrollbar and it should just work.

**Comment by wealstarr** [comment]
@K4sum1 

yay!!! 

I love you (in a respectful way)

![Capture](https://github.com/user-attachments/assets/fd69ac60-30a8-4db3-b1be-c133c4af2e6c)

Thank you from the core of my heart.

The colors of the buttons when hovering is all blue, here I found it on the rectify repo, this one also fixes that problem

```
.titlebar-button{
  background-color: transparent !important;
  -moz-context-properties: stroke !important;
  stroke: currentColor !important;
}
.titlebar-button:hover{ background-color: hsla(0,0%,100%,.32) !important }
.titlebar-close:hover{ background-color: hsl(355,86%,49%) !important }

.titlebar-close{ list-style-image: url(chrome://browser/skin/window-controls/close.svg) !important }
.titlebar-min{ list-style-image: url(chrome://browser/skin/window-controls/minimize.svg) !important }
.titlebar-max{ list-style-image: url(chrome://browser/skin/window-controls/maximize.svg) !important }
.titlebar-restore{ list-style-image: url(chrome://browser/skin/window-controls/restore.svg) !important }
```

Oh! that MacOS scrollbars hack work too.

Tell me your address so I can bring some sweets (just kidding)

Sorry, too happy.

**Comment by wealstarr** [comment]
@K4sum1 Please integrate the above code into r3dfox, make it default. I wouldn't have to bookmark this comment

**Comment by the-r3dacted** [comment]
It should be in 131 when I get it out
