### ISSUE TITLE
Commits trimmed from latest release

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#39]
These commits weren't reverted for the latest 124 release. They seem to do nothing, and therefore weren't reverted to simplify the update process. If you encounter an issue and one of these seem to be related, please let me know.

https://github.com/Eclipse-Community/r3dfox/commit/a43de70a1a7f3479b4331c548083e9940bfa38a7 There is no need for this code to run on pre-10, but it also doesn't affect anything.
https://github.com/Eclipse-Community/r3dfox/commit/83b286649bd3e984857ffdf73fba1d2a8a59ad00 Profiler isn't very likely to be used, and stub shouldn't be an issue. I haven't seen this break anything in testing.
https://github.com/Eclipse-Community/r3dfox/commit/44c2deaf1a155eb8bc74349b9ed030c0f2ca68d9 defaultagent shouldn't have any reason to show notifications anyways, doesn't seem to break anything.
https://github.com/Eclipse-Community/r3dfox/commit/8a6d9a46d0c9b2f35adc814995e05e69ffc5d91b Parental controls sucks. The code for this should just be stripped out entirely.
https://github.com/Eclipse-Community/r3dfox/commit/5b8d92872e153dfb0e3a3aee3a81416a33b6d9bd Also parental controls.
https://github.com/Eclipse-Community/r3dfox/commit/a5e6f6c1ab4aa061660e8d471af7624f3d439d85 Not sure where you would even see this, doesn't seem to effect anything.
https://github.com/Eclipse-Community/r3dfox/commit/5647f7c0f52cf81271aa0a8cef9fdd0dfb77fe9a Supposedly only a issue pre-7 which the extended kernels already have.
https://github.com/Eclipse-Community/r3dfox/commit/9ade0475405512439262f9441cb3d07cd17e098c Chromium Edge can run on 7, idk why there's a version check here.
https://github.com/Eclipse-Community/r3dfox/commit/26001e89730f84e33d45342874b919a6ba67e6c0 r3dfox assumes he user has VC++ installed and therefore d3dcompiler_47.dll in system even on 7. Also d3dcompiler_46.dll is no longer shipped, so not needed.
https://github.com/Eclipse-Community/r3dfox/commit/26b46fe1aece05947543d731621cd851d44cd7bb This seems to only be an issue for XP where TLS 1.2 isn't a thing. Since crash reports won't be going to Mozilla and if I want to make crashreporter useful I can just have it go over http to my own server, it's not a concern.
https://github.com/Eclipse-Community/r3dfox/commit/65a2fe6c621dfd6512468805f4bb73515eb5da26 Dependency on a below commit that I didn't revert, so not a issue.

These were partially reverted:

https://github.com/Eclipse-Community/r3dfox/commit/c5739e2655474a52ae4ce42d42dbda32a46a7178 Only AvailableMemoryTracker.cpp was reverted. the nsXPCOMGlue changes don't have any effect here since r3dfox assumes the user has VC++ installed and it doesn't ship with Universal CRT DLLs.
https://github.com/Eclipse-Community/r3dfox/commit/31e3d8a68ad8bf96af5dd9998c61476651abee1d The two MenuTouchModeObserver version checks seem to be a non-issue since they were later made available to all operating systems. I assume since it's allowed for macOS and Linux it will work on 7 too. However I can't test. aboutSupport.js security software stuffs seem weird, I'm not sure why 7 wouldn't support it, but even if not it's just blank and a minor visual bug.
https://github.com/Eclipse-Community/r3dfox/commit/bcd7d268c4e0172d55dc905e36199b8274214e9e AboutWelcome stuff not reverted since unused in r3dfox,

**Comment by adeii** [comment]
Commits that effect on browser/omni.ja caused problem and forced close browser.
Older version of _omni.ja/defaults/settings/*_ and _omni.ja/moduls/*.mjs_ works fine on Win 7. Also 124.0.3 works fine.

**Comment by the-r3dacted** [comment]
> Commits that effect on browser/omni.ja caused problem and forced close browser. Older version of _omni.ja/defaults/settings/*_ and _omni.ja/moduls/*.mjs_ works fine on Win 7. Also 124.0.3 works fine.

What do you mean by this? What is broken?

**Comment by adeii** [comment]
I don't know exactly to tell. Librewolf 124.0.1 got the same problem with force close after 90 sec.
So I had changed all libs from your R3dfox 124.0.3 and still got problem.
So after copying only browser/omni.ja to original Librewolf 124, it runs normal even after 3 minutes.
So, some trimmed commits from gecko-dev, solved problem with force close in R3dfox 124.0.3 !
But that problem was also in R3dfox 124.0.2 32bit.

**Comment by the-r3dacted** [comment]
Oh, the force close is because you have an old profile. Is browser.taskbar.lists.legacyBackend set to false in r3dfox? If so, you might need to edit your user.js to set it to true.

**Comment by adeii** [comment]
I got force close even on deleting all profiles in AppData/Local, and in portable versions, too.
Thanks for info. Is it could also be set to true via about:config?

**Comment by the-r3dacted** [comment]
No, it always crashes if you try setting it to true that way.

**Comment by the-r3dacted** [comment]
Seems to be no issues and I undid some reverting for 126.

**Comment by adeii** [comment]
You got this! r3dfox 126! Further compatibility for Win 7 than VxKex.
