### ISSUE TITLE
Remove setup internet ping

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#44]
The setup seems to contact 34.120.208.123 and maybe other addresses on the IP range when closed. Not sure what it's doing, but I don't like it.

**Comment by jonm58** [comment]
what?GOOGLE CLOUD PLATFORM?

**Comment by the-r3dacted** [comment]
I will likely do this for 125 as I want to get 124 final out, and I doubt it's doing much.

**Comment by the-r3dacted** [comment]
This should be fixed in 125.

https://github.com/Eclipse-Community/r3dfox/releases/tag/125.0rc
