### ISSUE TITLE
My tests are version 124.0.3.

### ISSUE THREAD

**Issue by EDSln** [Eclipse-Community/r3dfox-old#46]
Did a couple of tests on different OS. Windows 7 x32 on Pentium 4, version 124.0.3 x32 works well, there is hardware acceleration (AMD HD3850AGP video card). 
![7-32](https://github.com/Eclipse-Community/r3dfox/assets/34573155/a3af1547-44c4-4614-8e10-4dc5f719637d)
And XP x64 with installed OneCoreApi Canary 4.0.0.0 in a virtual machine, 124.0.3 x64 also works without errors.
![xp-64](https://github.com/Eclipse-Community/r3dfox/assets/34573155/0324284c-d12f-4d92-a9fb-70d04c190895)

**Comment by the-r3dacted** [comment]
Cool! But like is there a reason this is an issue?

**Comment by EDSln** [comment]
No, it's not a issue. I just haven't found any other way to report my tests. :)

**Comment by the-r3dacted** [comment]
https://board.eclipse.cx/viewtopic.php?t=623

**Comment by TRX99** [comment]
> https://board.eclipse.cx/viewtopic.php?t=623

I installed version 124.0.3 ( nor 124.0.3-hotfix) and the main problem was tampering with the default theme. I changed the theme to Light, but there is still a dark purple color in the internal parts of Firefox, such as Settings or Clear All History

I said before, please don't touch the default theme and default color of Firefox, and if any user wants, he can change the theme according to his own taste, exactly what Firefox does and always provides the default theme.

**Comment by the-r3dacted** [comment]
> I installed version 124.0.3 ( nor 124.0.3-hotfix) and the main problem was tampering with the default theme. I changed the theme to Light, but there is still a dark purple color in the internal parts of Firefox, such as Settings or Clear All History

Under Language and Appearance try setting website appearance to Light.

**Comment by TRX99** [comment]
> > I installed version 124.0.3 ( nor 124.0.3-hotfix) and the main problem was tampering with the default theme. I changed the theme to Light, but there is still a dark purple color in the internal parts of Firefox, such as Settings or Clear All History
> 
> Under Language and Appearance try setting website appearance to Light.

The problem was not solved. Still the inner parts are dark. The home page of Firefox and the tabs are light, but the inner parts are dark.

![a1](https://github.com/Eclipse-Community/r3dfox/assets/76468679/f32b3bc0-21ee-4717-a5f8-3a63eb767729)
![a2](https://github.com/Eclipse-Community/r3dfox/assets/76468679/beddadee-e890-4a92-be08-3530718c6c75)

**Comment by the-r3dacted** [comment]
I guess I'll try finding a different way come 125.

**Comment by the-r3dacted** [comment]
Doesn't need to be an issue.
