### ISSUE TITLE
Dark Mode disable

### ISSUE THREAD

**Issue by noles22** [Eclipse-Community/r3dfox-old#49]
All web pages are displaying in dark mode starting with 124.0.3 even after I went to about:addons and selected the light theme. I'm running Windows 7 SP1 and am using the 64-bit build of the browser. I would just like to know how to turn off dark mode for webpages

**Comment by the-r3dacted** [comment]
I will undo this change in 125.

For now, under Language and Appearance try setting website appearance to Light.

**Comment by noles22** [comment]
Ok thanks

**Comment by the-r3dacted** [comment]
Default is back to light mode in 125.

https://github.com/Eclipse-Community/r3dfox/releases/tag/125.0rc
