### ISSUE TITLE
Problem with Spotify on Windows 8.1

### ISSUE THREAD

**Issue by GustavoJadson** [Eclipse-Community/r3dfox-old#50]
When trying to use Spotify on the browser, it gives me the message "Spotify can't play this right now. If you have the file on your computer you can import it."
Spotify works on Waterfox latest.
Didn't tested Deezer nor Netflix.

**Comment by the-r3dacted** [comment]
Might be some weird DRM type thing, seeing NT 6.3 with latest Firefox isn't exactly normal.

**Comment by wealstarr** [comment]
> works on Waterfox latest.

Which version of Waterfox did you tested ?

**Comment by the-r3dacted** [comment]
I am disabling all DRM.
