### ISSUE TITLE
Ruffle enabled .swf files not loading

### ISSUE THREAD

**Issue by Padre2** [Eclipse-Community/r3dfox-old#51]
I have _.swf_ files on websites that are enabled by installing a Ruffle component file on the websites, which allows them to display normally.
I am running Eclipse r3dfox 125 (64-bit) on Windows 7 Professional. 
For all these files on different websites, I am getting messages as follows:
Ruffle failed to load the required "_.wasm_" file component.
For reference regarding Ruffle, see: https://ruffle.rs/
This problem does not occur with Firefox 109esr, or any of the other major browsers.

**Comment by the-r3dacted** [comment]
Can you try with regular Firefox on 10 VM or with VxKex on 7?

**Comment by Padre2** [comment]
Thank you for your quick response.

My apologies, but I don't understand some of your instructions. I don't have any problem with the display on regular Firefox ver. 109esr and don't understand "10 VM".

I found VxKex and installed the latest release and entered r3dfox.exe as the application. After installing, I cleared the server and browser caches and opened the pages that had had the issue of Ruffle failing to load the required ".wasm" file component and it had been fixed. Thank you again for your assistance.

Fyi, I am interested in using the r3dfox browser because it has the best CSS performance of any browser on Windows 7 to display a particular animated graphics file that I am using. It seems even more responsive with this file than Chromium-based browsers on Windows 10.

**Comment by the-r3dacted** [comment]
10 VM means Windows 10 in a virtual machine. Although testing on a Windows 10 PC would also work. I also mean VxKex for regular release level Firefox. Although since 125 is still RC, you'll need to get the Firefox beta release.

**Comment by Padre2** [comment]
Thanks for the explanation. I assumed virtual machine, but confused by the 10.

**Comment by the-r3dacted** [comment]
Wait, you said VxKex fixed it. I had missed that. I want this to work stock, without VxKex.

Can you check earlier releases to see where it began?

**Comment by the-r3dacted** [comment]
Or wait, why don't I test it

**Comment by the-r3dacted** [comment]
I tried testing https://ruffle.rs/demo/, and it works on 125 stock for me. Will test on hardware then I guess.

**Comment by the-r3dacted** [comment]
![WorksOnMyMachine](https://github.com/Eclipse-Community/r3dfox/assets/77039240/6113bbc5-0296-4bd0-aa69-28fc2fc1f697)

**Comment by the-r3dacted** [comment]
Try running without VxKex and disabling javascript.options.wasm_multi_memory in about:config
