### ISSUE TITLE
Desktop only script not working.

### ISSUE THREAD

**Issue by Padre2** [Eclipse-Community/r3dfox-old#52]
I have a site which uses script to exclude parts of pages from displaying on mobile screens.
I am running Eclipser3dfox  125 (64-bit) on Windows 7 Professional.
On Eclipse r3dfox  this script is also excluding the display of these parts of pages from displaying on desktop screens.
This problem does not occur with Firefox 109esr, or any of the other major browsers.

**Comment by the-r3dacted** [comment]
Can you try with regular Firefox on 10 VM or with VxKex on 7?

Also what is the script? What does it look at?

**Comment by Padre2** [comment]
The script is in a plugin on a WordPress site.  It prevents the loading of parts of certain pages that will not display on mobile screens.

Per my other post regarding the Ruffle issue, I installed VxKex. It also solve this script issue. Thank you.

**Comment by the-r3dacted** [comment]
I assume it has some weird coding and shits itself when it sees Windows 7 useragent with Firefox post 115. It would probably be easier for me to just test myself if you can give me something to test these issues.

**Comment by Padre2** [comment]
I presume I can continue to use VxKex with r3dfox , if it solves both problems?

If you are interested to look at the plugin code, here is the link:
https://wordpress.org/plugins/mobile-only-desktop-only-content/?ref=commonninja

For the Ruffle files that are installed on the server to display .swf files, you can get the latest from the following link:
https://github.com/ruffle-rs/ruffle/releases/download/nightly-2024-04-15/ruffle-nightly-2024_04_15-web-selfhosted.zip
