### ISSUE TITLE
m$ bad button

### ISSUE THREAD

**Issue by jonm58** [Eclipse-Community/r3dfox-old#57]
Maybe this is why Mozilla makes its own css title bar?
good:
![image](https://github.com/Eclipse-Community/r3dfox/assets/73036321/45bf4093-7574-4e58-9afc-e8167a949e47)
![image](https://github.com/Eclipse-Community/r3dfox/assets/73036321/7e46b4c6-3661-4c32-af76-b74c7deb7ccc)
bad:
![image](https://github.com/Eclipse-Community/r3dfox/assets/73036321/de02662f-e63b-4c40-bf26-909603121e0b)

I'm use css themes:
all from https://github.com/datguypiko/Firefox-Mod-Blur
acrylic_micaforeveryone.css
cleaner_extensions_menu.css
no_search_engines_in_url_bar.css
thin_scrollbar_windows10.css
wallpaper-edition.css

**Comment by JonnyThree** [comment]
seems to be that the Minimize, Maximize, and Close buttons are gone. i have also this kind of  bug in latest Release v125.0.2

**Comment by the-r3dacted** [comment]
I'm closing this in favor of making a new issue where I can better describe the issue
