### ISSUE TITLE
Missing settings options

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#58]
These are missing from r3dfox and idk why.

![image](https://github.com/Eclipse-Community/r3dfox/assets/77039240/6bd4ff2a-ddf5-4b7e-ab71-7fc6b23e0b59)

![image](https://github.com/Eclipse-Community/r3dfox/assets/77039240/f352ac8d-4d35-4e18-a84c-e2eccd792904)

**Comment by the-r3dacted** [comment]
First one I just bypassed by disabling the popup. Second I have added.

**Comment by i486** [comment]
I'm unsure if these three options have intentionally been disabled, as I couldn't locate them in the r3dfox settings. Just wanted to bring it to your attention in case it's a glitch.

![image](https://github.com/Eclipse-Community/r3dfox/assets/625325/31683b3a-9b7b-4ab5-b1e8-9d7a3e44f799)

![image](https://github.com/Eclipse-Community/r3dfox/assets/625325/4e262f38-0d64-40d1-9a62-37fdea27ba22)

**EDIT: DRM was disabled**
https://github.com/Eclipse-Community/r3dfox/issues/50#issuecomment-2059658380
https://github.com/Eclipse-Community/r3dfox/issues/47#issuecomment-2059658784

**Comment by the-r3dacted** [comment]
For those two in the yellow box, they're restricted to 10+, so when I undo the commits that broke 7, they disappear. I see you figured out disabled DRM.

I'll get to your other comments in a bit, did this now since it's so basic.
