### ISSUE TITLE
{Query} Can we expect a version of Thunderbird 125 for Win 7? 

### ISSUE THREAD

**Issue by EDSln** [Eclipse-Community/r3dfox-old#60]
Thunderbird 125 has been released, requiring Win 10. Do you plan to make a version for Win 7?

**Comment by i486** [comment]
Have you tried [VxKex ](https://github.com/vxiiduu/VxKex)?

**Comment by EDSln** [comment]
The 125 version runs with VxKex (but the 126 version doesn't even run with VxKex). But by this logic r3dfox is not needed either, I can run Firefox 125 via VxKex. That's why I'm asking if I can expect Thunderbird not requiring VxKex.

**Comment by the-r3dacted** [comment]
There's no real need for a modern browser engine with email. You're not running complex scripts or anything, just basic HTML and CSS. I recommend using roytam1's mailnews which has XP compatibility too. Might fork it and add a portable mode sometime.

https://o.rthost.win/boc-uxp/?sort=date&order=desc

**Comment by the-r3dacted** [comment]
Not Thunderbird 115, but it is what I use now.

https://github.com/Eclipse-Community/eMail
