### ISSUE TITLE
Missplaced tick boxes in settings

### ISSUE THREAD

**Issue by bnw42** [Eclipse-Community/r3dfox-old#61]
I couldn't see an issue about this, so posting it as a new one. On version 125.03 when going to settings, for those settings where there is a tick box followed by a description of the setting, the tick box is sitting on top of the first letter of the description. Hopefully the screen shot uploads here:
![Noname](https://github.com/Eclipse-Community/r3dfox/assets/32752056/09927bc9-0646-4449-9ee1-6899b5aba2fc)

When I installed r3dfox I did replace the profile folder with that from the existing FF115ESR install, which has been heavily hardened and tweaked, so I'm unsure if it is a bug or an artifact created by copying over the profile. 

Also in the settings, r3dfox doesn't seem to be able to pick up the English (GB) dictionary. It should have been carried over with the profile, I manually installed it but it still only shows English (US) as the only option.

**Comment by bnw42** [comment]
I rebooted r3dfox and the GB dictionary finally showed up. So I'll retract that one. :)

**Comment by the-r3dacted** [comment]
Maybe you have some sort of userChrome.css in your profile folder that is breaking something? I haven't seen this issue in any of my testing.

**Comment by bnw42** [comment]
This is the userchrome.css file from FF, which would have been ported over. It moves the tabs to below the bookmarks bar.

#titlebar{
order: 2;
-moz-appearance: none !important;
--tabs-navbar-shadow-size: 0px;
}
:root{ --uc-window-control-width: 0px !important }
#navigator-toolbox{ padding-top: calc(20px + var(--uc-titlebar-padding,0px)) !important }
#toolbar-menubar{
position: fixed;
display: flex;
top: var(--uc-titlebar-padding,0px);
height: 29px;
width: 100%;
overflow: hidden;
}

**Comment by the-r3dacted** [comment]
At a glance it doesn't seem like it would do it, but I guess see what happens without it anyways.

Also what OS and theme are you using?

**Comment by bnw42** [comment]
Win7 and the default theme.

**Comment by the-r3dacted** [comment]
I can't replicate it on my end with Aero or Basic themes. Do you have anything else in the userChrome folder? If not, try renaming the profile folder and see what happens.

**Comment by bnw42** [comment]
I disabled userChrome and it made no difference. SO whilst I was in the chrome folder I disabled userContent.css and that fixed the glitchy settings. The contents of userContent.css, deleting bumf is:

/* about:addons *************************************************************************/
@import url(./css/aboutaddons/addons_manager_alternative_appearance.css);
@import url(./css/aboutaddons/addonlists_show_addon_version_number.css);
@import url(./css/aboutaddons/recentupdates_category_always_visible.css);
@import url(./css/aboutaddons/description_page_alternative_content_order.css);

/* about:preferences ********************************************************************/
@import url(./css/aboutpreferences/preferences_alternative_appearance.css);

One of those is clearly the culprit. I think the userContent.css is a legacy from an old FF tweak/fix since it's dated 2017. After removing it I didn't notice any obvious change in r3dfox. Either way, it causes the glitches in settings in r3dfox but not FF115ESR.

**Comment by the-r3dacted** [comment]
I guess the thing is outdated or doesn't work with native controls patch, or both. I guess try getting a updated userContent.css and see if that fixes it.

Since this isn't a browser issue, and I can't guarantee compatibility with modifications, I'm closing this.

**Comment by bnw42** [comment]
And removing the userContent.css made no difference to the appearance (apart from eradicating the glitch) so it is evidently redundant. :)
