### ISSUE TITLE
Fixing VirusTotal false positive

### ISSUE THREAD

**Issue by rovickti** [Eclipse-Community/r3dfox-old#63]
VirusTotal has different false positive each for the 2 downloads I tested:

[r3dfox-125.0.3.en-US.win64.installer.exe](https://www.virustotal.com/gui/file/59eb205003f27052f39b8ee72e0b6f274313d3a4061b41e6ffb3601b29fda33c): Zilya, Palo Alto Networks
[r3dfox-125.0.3.en-US.win64.portable.7z](https://www.virustotal.com/gui/file/9d12cfcfee952844c221a61ed00f4bdeb2bf5ed5b9a3f3d77e43d7564992d9bc/detection): VirIT

The portable version has a different scanner report an issue, while that scanner doesn't have a problem with the exe installer. You're packaging both versions yourself, right?

Edit: the portable one seems to have cleared itself when I reanalyzed just now 0/55.

New people might want to check VirusTotal before using software for the first time, so it looks better if VirusTotal has a clean report.

Sourceforge submits automatically I think, but these scanners have been slow to whitelist despite r3dfox being a browser - e.g. [123.0.2](https://www.virustotal.com/gui/file/59da8e92350eb6c4ab3877d08326ca3eade77c3a90367d35c680f6b2ad698833/details) has a false positive so this issue has been around for a while.

The AV companies have their false positive contact emails listed. Introducing the project, giving the homepage, and github/sourceforge download pages might encourage them to monitor in future: 
https://docs.virustotal.com/docs/false-positive-contacts

**Comment by the-r3dacted** [comment]
Seeing as it automatically clears itself I think it's fine. Anyone familiar with Virustotal knows that a few false positives are a given.
