### ISSUE TITLE
Autoconfig js - is it supported here?

### ISSUE THREAD

**Issue by Uber-1** [Eclipse-Community/r3dfox-old#64]
Original Firefox and Waterfox can be configured via "defaults\pref\autoconfig.js"+"autoconfiglocal.js" in program folder.

Examples of these configs:

autoconfig.js
`
// autoconfig.js file needs to start with a comment
pref("general.config.filename", "autoconfiglocal.js");
pref("general.config.sandbox_enabled", false);
pref("general.config.obscure_value", 0);
`

autoconfiglocal.js
`
// Mozilla User Preferences
defaultPref("browser.cache.disk.enable", false);
defaultPref("browser.fullscreen.animate", false);
`

But r3dfox shows this for each start
![2](https://i123.fastpic.org/big/2024/0505/f3/21486e19c1df940de5bc515f5c361bf3.png)

Then you can close it and browser starts.

Can you fix this?

**Comment by the-r3dacted** [comment]
Can you test on stock Firefox 125 either on 10 or with VxKex? If it doesn't occur there, then try previous releases until you get to one that works.

**Comment by jonm58** [comment]
r3dfox with Autoconfig js on win 11 22000 NP

**Comment by jonm58** [comment]
![image](https://github.com/Eclipse-Community/r3dfox/assets/73036321/d7187422-dba9-45e8-93b7-1459b2674e7f)
![image](https://github.com/Eclipse-Community/r3dfox/assets/73036321/64f1464e-e3db-4f91-ad18-71aede47a1d7)

**Comment by jonm58** [comment]
> autoconfig.js `// autoconfig.js file needs to start with a comment pref("general.config.filename", "autoconfiglocal.js"); pref("general.config.sandbox_enabled", false); pref("general.config.obscure_value", 0);`
> 
> autoconfiglocal.js `// Mozilla User Preferences defaultPref("browser.cache.disk.enable", false); defaultPref("browser.fullscreen.animate", false);`

Can I see your autoconfig.js and autoconfiglocal.js files?

**Comment by Uber-1** [comment]
You may also try these ready-to-use files:
https://0x0.st/X8Hg.JS/autoconfig.js
https://0x0.st/X8HY.JS/autoconfiglocal.js

**Comment by jonm58** [comment]
I was unable to reproduce the problem

The problem may be in your operating system

**Comment by adeii** [comment]
Off topic.
You can enable WebGL (1) by default if used  _pref("webgl.disabled", false);_ in some *.js or *.cfg.
