### ISSUE TITLE
Add back UserAgentOverrides.jsm

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#67]
I assume this wouldn't be too hard. I mostly want it to fix websites if I add r3dfox back to the UA string if I ever decide to do so.

https://bugzilla.mozilla.org/show_bug.cgi?id=1513574

This would be a precursor to that if it happens.

**Comment by the-r3dacted** [comment]
Will be in next release of 128

**Comment by ghost** [comment]
I'm against the idea of setting per domain user agent override in about:config.

**Comment by ghost** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1513574 clearly shows why Mozilla decided to remove this feature. It's a bad practice and it's bad for performance, too. Anyone experiencing problems with user agent and wanting to set per domain custom user agent can install an addon to do so. Please don't pollute about:config! Abusing about:config for stuffs like that is bad, it's even worse for the developer to set them by default!

**Comment by the-r3dacted** [comment]
They removed it because they now use something locked away from a fork creator like me. It gives them more control.

**Comment by ghost** [comment]
Not everything Mozilla does is bad. They clearly said they moved the JavaScript code to C++ and expose it via the WE API. This will improve performance and stop about:config from being abused. What you did is bring back the removed JavaScript code. People can simply use the WE-based addon to change user agent the easier way and with better performance.

**Comment by jonm58** [comment]
Floorp did too,why need addon.

**Comment by ghost** [comment]
> Floorp did too,why need addon.

Floorp is not absolute truth. What Floorp done is not necessarily right.
