### ISSUE TITLE
Release v126.0-2 and user language setting

### ISSUE THREAD

**Issue by bnw42** [Eclipse-Community/r3dfox-old#68]
Not an issue but just a FYI. Whilst the previous version reset the user language to en-US (for at least some users), on upgrading to 126.0-2 the language stayed with what I had previously had it set as and did not reset it to en-US.

**Comment by the-r3dacted** [comment]
I still get notifications for the old issue, making a new one is pointless. I assume it's the same since it's the same internal version number. I think it just needs to update the language from Mozilla's server with each new release since I only build for en-US.
