### ISSUE TITLE
hardware acceleration in webgl1 and webgl2

### ISSUE THREAD

**Issue by greyrat116** [Eclipse-Community/r3dfox-old#69]
must be switched
webgl.disable-angle - true
webgl.force-enabled - true

**Comment by the-r3dacted** [comment]
What is this for?

**Comment by jonm58** [comment]
> What is this for?

webgl2
Software renderer can't use webgl2

**Comment by the-r3dacted** [comment]
Ok, but why should I set these?

**Comment by jonm58** [comment]
> Ok, but why should I set these?

webgl2 and hardware acceleration

**Comment by the-r3dacted** [comment]
Isn't webgl useless and a security risk? I have it disabled in my browsers.

**Comment by jonm58** [comment]
> Isn't webgl useless and a security risk? I have it disabled in my browsers.

https://play2048.co/

**Comment by greyrat116** [comment]
All 360 video https://www.youtube.com/results?search_query=360%C2%B0

**Comment by the-r3dacted** [comment]
So I tried 2048 and it worked completely fine with software rendering even.

I guess 360 degree video would make sense. I thought YouTube killed that ages ago though. They have so much JS can't they just implement it in that?

**Comment by greyrat116** [comment]
https://earth.google.com/web/
In addition to Google, some regional sites with maps of the area or even weather have Webgl elements.

**Comment by greyrat116** [comment]
> I guess 360 degree video would make sense. I thought YouTube killed that ages ago though. They have so much JS can't they just implement it in that?

There is a GPU for 3D, why shift it to a CPU?

**Comment by the-r3dacted** [comment]
So I tried this, and WebGL1 seems to be taken care of by ANGLE. If I disable ANGLE, I don't get WebGL1. I am doing this testing in a VM which satisfies WebRender enough to do "hardware" acceleration. This might be a regression for some users who can only use ANGLE.

> There is a GPU for 3D, why shift it to a CPU?

1: Hardware acceleration is buggy for me on my main system.

2: I have 16 cores and rather have my GPU used for a task that needs it.

**Comment by greyrat116** [comment]
In win7, Webgl Angle does not work at all (I have GTX260 dx10). probably available from dx11.
Opengl webgl1 is available on all opengl 2.0 graphics cards (Radeon 9500, GF6100, GMA X3100)

Hardware Webrender does not work in Win7

**Comment by the-r3dacted** [comment]
idk, I'll just leave this as the user will know best idk what to do here.
