### ISSUE TITLE
Content Playback Issue

### ISSUE THREAD

**Issue by DzaminNayura** [Eclipse-Community/r3dfox-old#71]
When attempting to play DRM protected content on sites such as Netflix/Prime Video, there will be an error.

An example of such an error(FF based):
"Digital Rights Error
Your web browser is missing a digital rights component.
In your web browser's address bar, type about:addons, press Enter, and then on the left, click Plugins. For the Widevine Content Decryption Module, select Always Activate, and then refresh the video's page and try watching the video.

If the video doesn't play, go back to Plugins, click the gear icon at the top of the page, and then click Check for Updates. When the plugins have updated, refresh the video's page, and then try watching the video."

Mozilla's guide for reference: https://support.mozilla.org/en-US/kb/enable-drm

Steps taken to try to fix the issue:
1) Download the widevine plugin from mozilla github:
https://github.com/mozilla/gecko-dev/blob/master/toolkit/content/gmp-sources/widevinecdm.json
For Windows 64 bit this is the correct plugin -
"WINNT_x86_64-msvc": {
  "fileUrl": "https://redirector.gvt1.com/edgedl/widevine-cdm/4.10.2710.0-win-x64.zip"
  
    Win 32bit, Win Arm64 and others also included in the repo.
  
 2) Open about:support, find "Profile Folder", click "Open Folder"
 
 3) Create a folder named "gmp-widevinecdm, then unzip the widevinecdm zip file downloaded earlier, copy the folder extracted, "4.10.2710.0-win-x64" to the "gmp-widevinecdm" folder, anything named widevinecdm as well as the manifest Json should be in the folder.
 
 4) Rename "4.10.2710.0-win-x64" to "4.10.2710.0", once done, enter about:addons in the address bar, under "plugins", "manage your plugins" you should now see widevinecdm show up but it's grayed out and disabled at least once with no option to activate it, subsequent navigation to the addons page should no longer display the plugin (config/support problem?).
 
 5) Open about:config, right click, select New, then String, add these:
 media.gmp-widevinecdm.version   4.10.2710.0
 media.gmp-widevinecdm.abi   x86_64-msvc-x64
media.gmp-widevinecdm.enabled   true
media.gmp-widevinecdm.hashValue  (get hash from 115 esr)
Hash may work from Win10 and above pc firefox(not tested)
 
 The following entries may or may not be auto filled or have already been included by the browser itself:
 media.gmp-widevinecdm.lastDownload
 media.gmp-widevinecdm.lastInstallStart
 media.gmp-widevinecdm.lastUpdate
 media.gmp-widevinecdm.visible   true
 media.widevine.hdcp-protection-mask   true
 Nevertheless, I added it from 115 esr about:config just in case.
 
 Restart R3dfox, drm error still persists after manual installation, copying the widevine plugin from Esr yields the same results.
 Notably, the "Digital Rights Management (DRM)" Content option as well as the "Play DRM-controlled content" checkbox in about:preferences#general, present in Firefox ESR is missing in r3dfox, indicating a lack of support for DRM content.

As of Firefox ESR 115.11.0,
Widevine CDM, which is needed for Playback for HDCP protected content (DRM) such as Netflix/Amazon Prime Video/Disney+/HULU/Crunchyroll etc is included, enabled and tested still working so this isn't an OS (Win7/8) problem.
I've not tested whether the widevine plugin/config from Win10 and above pc (I have 2 at home) with firefox standard/dev/nightly works but realistically, it shouldn't as the config/platform is different.

Test Setup - Win7 and 8.1 PC, 4790K, 6800K (DDR3/4) platforms
GPUs: 3090 on W7, 1080Ti on W8.1
Browser on SATA SSDs, HW acceleration enabled
Tested both portable and Installation versions.

**Comment by the-r3dacted** [comment]
I build with DRM disabled. If you want it, see if Mercury-Win7 has it.
