### ISSUE TITLE
Google Widevine

### ISSUE THREAD

**Issue by noles25** [Eclipse-Community/r3dfox-old#72]
The Google Widevine plugin isn't showing up under plugins like it is in Firefox so I'm not able to play back any DRM-protected videos is there a way to manually add it to r3dfox?

**Comment by i486** [comment]
Unfortunately, it's disabled. Personally, it doesn't affect me much as I stopped using legitimate streaming sites about a year ago. But if I were still using them, it'd be quite annoying. Anyway, I'd recommend giving the latest Firefox with VxKex a shot to see if it the DRM sites works or not.

For more details, check out these GitHub issues:

    [Issue 71](https://github.com/Eclipse-Community/r3dfox/issues/71)
    [Issue 50](https://github.com/Eclipse-Community/r3dfox/issues/50)
    [Issue 47](https://github.com/Eclipse-Community/r3dfox/issues/47)

@K4sum1

I'm intrigued by how the DRM code meshes with the Firefox code. Does it also rely on Windows 10+ APIs and require extensive work to undo/patch? If not, and if Firefox with VxKex DRM handles DRM streaming sites well, would you consider releasing a DRM-enabled build alongside the regular one in the future? Or maybe have everything disabled by default and let users activate it via about:config?

**Comment by the-r3dacted** [comment]
It should* just work on 7. I don't want DRM running in my browser, nor do I have a way to test if it's broken. Why I suggest https://github.com/Alex313031/Mercury-Win7
