### ISSUE TITLE
Fullscreen transition not working

### ISSUE THREAD

**Issue by bbc-chi** [Eclipse-Community/r3dfox-old#73]
The transition of videos switching to fullscreen doesn't work. Normally the browser would spawn a “MozillaTransitionWindowClass” window for a smooth crossfade, but this doesn't happen with r3dfox. The prefs "full-screen-api.transition..." seem to be ok. Any chance you could fix that?

Longtime Wf user here... I switched to r3dfox two weeks ago and I'm not going back ;). Great work! The only thing missing, apart from the transition, would be the “about:performance” tab.

**Comment by the-r3dacted** [comment]
Can you go through previous versions and see where the issue began?

Also for about:performance, I found this. Seems to have been replaced with something better.
https://bugzilla.mozilla.org/show_bug.cgi?id=1836191

**Comment by bbc-chi** [comment]
> Can you go through previous versions and see where the issue began?
I tried r3dfox-125.0.3.en-US.win64.portable, r3dfox-125.0.2.en-US.win64.portable and then went back to the first release firefox-122.0.1.en-US.win64.installer, but no transition... Guess it never worked?!

> Also for about:performance, I found this. Seems to have been replaced with something better.
For better or worse :). With the TaskManager, for example, you can keep an eye on individual add-ons and track the performance... But with the ProcessManager there is no such thing. One line about Extensions and that's it.

![aboutperf](https://github.com/Eclipse-Community/r3dfox/assets/27514366/86e0e91a-ab65-4da4-a311-e6841ffdbe77)

**Comment by the-r3dacted** [comment]
Try these

https://github.com/Eclipse-Community/r3dfox/releases/tag/old

**Comment by bbc-chi** [comment]
> Try these
> 
> https://github.com/Eclipse-Community/r3dfox/releases/tag/old

The earliest version there was firefox-117.0.2.en-US.win64.installer.exe and also has no full-screen transition... I assume the other versions do too. Has it ever worked for you?

**Comment by the-r3dacted** [comment]
Hmm, if 117 still doesn't work, might need to go through the older 116/117 alpha builds until one breaks.

What is your OS setup, like version, theme, DWM on/off, etc?

**Comment by bbc-chi** [comment]
Ok, I found the problem:  Inside /widget/windows/nsWindow.cpp -> PrepareForFullscreenTransition() -> Line 3589 it reads: if (dwmCompositionEnabled) { return false; } which should be !dwmCompositionEnabled. Sure enough, when I switch off DWM I can see the transition window appearing :)

**Comment by the-r3dacted** [comment]
If it works without DWM, maybe I should just remove that bit of code all together then. I'll need to test to make sure it isn't buggy and then I can build.

I will say though, I had to downgrade my build machine. For now in my current config it takes 5 hours for each build.

**Comment by bbc-chi** [comment]
> If it works without DWM, maybe I should just remove that bit of code all together then.

I could see the transition window after switching off DWM, but it wasn't pretty. The comments above the bug state: 
  // We don't support fullscreen transition when composition is not
  // enabled, which could make the transition broken and annoying.
  // See bug 1184201.

> I will say though, I had to downgrade my build machine. For now in my current config it takes 5 hours for each build.

Yeah, that's rough... Thank you for your dedication :1st_place_medal:

**Comment by the-r3dacted** [comment]
Maybe a bit too quick on the draw to close now, but I have it fixed in the current master build of 126.0.2. I will release it when 126.0.2 goes official or when 127.0 gets merged to release, whichever happens first.

**Comment by bbc-chi** [comment]
Thank you, K4sum1! Fullscreen transition works as expected now with 127.0... Much appreciated :+1:
