### ISSUE TITLE
r3dfox v126.0.1 (x86) does not run on Windows 7 Ultimate SP1 (x86)

### ISSUE THREAD

**Issue by EgorKuzevanov** [Eclipse-Community/r3dfox-old#79]
![Untitled](https://github.com/Eclipse-Community/r3dfox/assets/78859951/777b4361-2943-4d63-b856-862aa708a5b9)
I have an Acer Aspire One ZG5 netbook (manufactured in 2008) with a 32-bit single-core double-threaded Intel Atom N270 processor (1,6 GHz), 1,5 GB of RAM and Intel GMA 950 integrated graphics. Microsoft Visual C++ 2015-2019 Redistributable Package v14.28.29213 (x86) installed.

**Comment by the-r3dacted** [comment]
Just pushed a 32 bit/x86 build of 127.0. Should fix the issue.

**Comment by the-r3dacted** [comment]
Closing since 126 is not able to run on RTM or unpatched SP1. 127 can run on it.
