### ISSUE TITLE
Will you release r3dfox 127 soon?

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#81]
I've already got Firefox 127 on my Windows 10 machine. Still waiting for r3dfox 127 for my Windows 8.1

**Comment by the-r3dacted** [comment]
RC 127 is the same, there are no differences between it and official release. I'll release 127.0.1 official when it comes out.

https://github.com/Eclipse-Community/r3dfox/releases/tag/v127.0rc2
