### ISSUE TITLE
Gecko Profiler no longer works

### ISSUE THREAD

**Issue by garry-ut99** [Eclipse-Community/r3dfox-old#86]
In Win 7 SP1, after updating to R3dfox 127, I've noticed recently that Gecko Profiler no longer works, and the big blue button is greyed out and can't be clicked:

>  Dev console (F12) > Performance tab: "Your platform is not supported. The Gecko Profiler only supports Tier-1 platforms."

![profiler](https://github.com/Eclipse-Community/r3dfox/assets/72945564/36cc82e2-08ed-4484-9ad2-50a81bf37e6e)

This https://github.com/Eclipse-Community/r3dfox/issues/9#issuecomment-2083200422 contains a link to profile:

> [r3dfox 125.0.3 youtube profiler](https://share.firefox.dev/4aUakC5)

 which means it was still working in R3dfox 125 / Firefox 125, so Mozilla disabled it in either FF 126 or FF 127, I didn't check whether they only disabled it or removed it completely.

**Comment by jonm58** [comment]
Configure options disable gecko profiler

**Comment by the-r3dacted** [comment]
For 126.0.2v, I disabled the profiler and kinda just carried that over to 127. I can enable it next build if needed.

**Comment by garry-ut99** [comment]
A good joke, isn't it? I hope it was just an April Fool's joke. Good to know, because nowhere there was a f...... word about it, neither in Releases page nor in Commits page, I only found this previous issue https://github.com/Eclipse-Community/r3dfox/issues/39, which mentioned something about Profiler, but it still was working fine, including R3dfox 125:
> [83b2866](https://github.com/Eclipse-Community/r3dfox/commit/83b286649bd3e984857ffdf73fba1d2a8a59ad00) Profiler isn't very likely to be used, and stub shouldn't be an issue. I haven't seen this break anything in testing. 

Removing silently an important feature for no reason and without consulting the community and without mentioning it anywhere = not a good idea. 

> Profiler isn't very likely to be used

It must be a joke.. Why do you think so? Why, after so many years of existence of such a great and useful tool like Profiler in Firefox, did you suddenly come to the conclusion that it would no longer be used? Even Mozilla didn't say anything like that, as it still does exist and is still used in Firefox on supported platforms like Win 10/11/Linux etc, Mozilla removed it only for unsupported pre-Win10 platforms like Win 7 / 8, because there is no need for them to keep old code which is unused on Win 10/11. It has nothing to with "Profiler is not useful anymore". Even in Chromium Profiler still does exist on supported platforms.

>  I can enable it next build if needed.

Lol. I hope so. Very needed, and not only for me, but for everyone who used it, as they still want to use it, I think that if you don't bring it back, many users will not like that. To have to use a browser which lacks a profiler tool? No thanks. I'd sooner think of switching to Win 10, than to stay on so much castrated version of browser.

**Comment by the-r3dacted** [comment]
![sorry](https://github.com/Eclipse-Community/r3dfox/assets/77039240/67724227-f9ba-42c6-94e2-7f00e5b2ea4f)

Currently building 127.0.1 which has it enabled again. Will be a couple hours until builds finish and I get it published.

**Comment by the-r3dacted** [comment]
Should work now in 127.0.1

https://github.com/Eclipse-Community/r3dfox/releases/tag/v127.0.1

**Comment by garry-ut99** [comment]
Works fine, I appreciate quick response & good job, don't worry :)
