### ISSUE TITLE
Mozilla Firefox 127.0.2 released some hours ago

### ISSUE THREAD

**Issue by Orthoxodus** [Eclipse-Community/r3dfox-old#88]

**Comment by the-r3dacted** [comment]
My response was going to be something along the lines of, yeah I'll eventually get around to it, but I decided to take a look and see if anything was worth bothering, and well, I am now working on getting 127.0.2 out.

**Comment by Orthoxodus** [comment]
> My response was going to be something along the lines of, yeah I'll eventually get around to it, but I decided to take a look and see if anything was worth bothering, and well, I am now working on getting 127.0.2 out.

Okay thanks for the response, we will help if needed. :)

**Comment by the-r3dacted** [comment]
Released 127.0.2

https://github.com/Eclipse-Community/r3dfox/releases/tag/v127.0.2

Also, by help, I am interested. What are you capable of?

**Comment by Orthoxodus** [comment]
> Released 127.0.2
> 
> https://github.com/Eclipse-Community/r3dfox/releases/tag/v127.0.2
> 
> Also, by help, I am interested. What are you capable of?

Recently I started to understand some things in the code, because I always loved GitHub, I always loved the design and etc.. For now, I understand the most basic things. I'm even glad I found this thing called GitHub. :)

**Comment by K4sum1** [comment]
> Recently I started to understand some things in the code, because I always loved GitHub, I always loved the design and etc.. For now, I understand the most basic things. I'm even glad I found this thing called GitHub. :)

I notice you have a bunch of Android repos, and well it would be really nice if you could help me with some things here: https://github.com/Eclipse-Community/build_lineage/issues

Or especially here: https://github.com/Eclipse-Community/build_lineage/issues/5

I am too busy with other projects to do this currently, and it's pretty low priority due to XZ1C being mostly fine to daily, but it would be nice to try the XZ2C again and have it fully working.

**Comment by Dachoni03** [comment]
> > Recently I started to understand some things in the code, because I always loved GitHub, I always loved the design and etc.. For now, I understand the most basic things. I'm even glad I found this thing called GitHub. :)
> 
> I notice you have a bunch of Android repos, and well it would be really nice if you could help me with some things here: https://github.com/Eclipse-Community/build_lineage/issues
> 
> Or especially here: [Eclipse-Community/build_lineage#5](https://github.com/Eclipse-Community/build_lineage/issues/5)
> 
> I am too busy with other projects to do this currently, and it's pretty low priority due to XZ1C being mostly fine to daily, but it would be nice to try the XZ2C again and have it fully working.

Allright, okay I will take a look at these things. :)

**Comment by Dachoni03** [comment]
With which custom rom the issues appearing?

**Comment by K4sum1** [comment]
I build my own Resurrection Remix Revived, which is LineageOS 17.1 based. That repo uses 10 sources I have forked under this organization, and basically is an easy way to get building them all.
