### ISSUE TITLE
Problem with playing any movies in Netflix

### ISSUE THREAD

**Issue by Orthoxodus** [Eclipse-Community/r3dfox-old#89]
![image](https://github.com/Eclipse-Community/r3dfox/assets/106074709/a950c0bf-51d3-429d-9d74-1597c010919d)

It is possible this to be fixed or with unsigned drm it's not possible, as I understand recently.

**Comment by the-r3dacted** [comment]
I do not build with Widevine or EME/DRM. I haven't tried to see if it's possible, but some older builds might have it. I suggest asking if @Alex313031 could do it in [Mercury-Win7](https://github.com/Alex313031/Mercury-Win7).
