### ISSUE TITLE
[FR] On Windows platforms, always set the OS to be "Windows NT 10.0"

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#90]
This is what Chrome has been doing for a while. Google has no good intentions, but this change really helps people running legacy Windows from being discriminated against by websites (since it's applied to supermium and other Chromium forks for legacy Windows, too).

**Comment by the-r3dacted** [comment]
r3dfox actually does the opposite. Windows 10+ are identified as 8.1 or 6.3 to websites. I do not want to artificially boost the marketshare of 10/11, and would much rather do the opposite which I have.

~~This actually was an unintentional side effect of getting Aero Glass able to be used on 10.~~

**Comment by jonm58** [comment]
we need a function to set the UA,like the Floorp Browser
(Yes,I know general.useragent.override)

**Comment by the-r3dacted** [comment]
general.useragent.override

**Comment by jonm58** [comment]
I mean this(put this in "about:preferences"):
![Floorp](https://github.com/Eclipse-Community/r3dfox/assets/73036321/517cf14f-e1ca-4b60-b3ea-75f7697a60bf)

**Comment by the-r3dacted** [comment]
Make an issue for it, and I'll get around to it eventually.

**Comment by ghost** [comment]
> general.useragent.override

Does this still work?

**Comment by jonm58** [comment]
> > general.useragent.override
> 
> Does this still work?

Yes,still work
![图片](https://github.com/Eclipse-Community/r3dfox/assets/73036321/0f291966-bcfb-48a6-aed7-8f7914544450)
