### ISSUE TITLE
Can you make Firefox 115.x ESR releases?

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#91]
Firefox 115.x ESR is still being supported by Mozilla.

**Comment by the-r3dacted** [comment]
I might make a 115 ESR for Vista. It's low priority though.

**Comment by ghost** [comment]
I'm on Windows 8.1 64 bit. Will it work for me, too?

**Comment by the-r3dacted** [comment]
Yeah. I figure r3dfox wouldn't offer much over stock 115 ESR, so I should make it worth it by making a Vista compatible release.

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/releases/tag/v115.13.0esr
