### ISSUE TITLE
Ubication prompt issues

### ISSUE THREAD

**Issue by socketpal25** [Eclipse-Community/r3dfox-old#93]
Is it normal that in the latest version of r3dfox websites can't detect the geolocation of my PC? I know that it might happen because of privacy reasons but there is one website that i need to access frequently (my college's website to be exact) and it asks for my PC's geographic location...

**Comment by socketpal25** [comment]
![Captura](https://github.com/Eclipse-Community/r3dfox/assets/167911618/60c63b50-7bc5-4687-8989-c63a4d5835ac)
(added picture in case you don't understand it)

**Comment by the-r3dacted** [comment]
Can't you just allow it? Firefox has it ask the user by default and so does r3dfox.

**Comment by jonm58** [comment]
in about:support
Google Location Services key: missing
Google Safe Browsing key: missing
Mozilla Location Services key:Missing

**Comment by socketpal25** [comment]
I got the same issues that jonm58 mentioned
![Captura](https://github.com/Eclipse-Community/r3dfox/assets/167911618/f248640c-a69f-40ec-883a-0c1568c8d7b6)

**Comment by jonm58** [comment]
https://developers.google.com/maps/documentation/geolocation/get-api-key?hl=en-us

Geo API:geo.provider.network.url

**Comment by socketpal25** [comment]
What should i do with this? I am not too tech savvy, sorry for any incovenience

**Comment by jonm58** [comment]
> What should i do with this? I am not too tech savvy, sorry for any incovenience

use this testing:https://browserleaks.com/geo

for me and you, just Allow Allow and **Allow**
Geo API will work

**Comment by the-r3dacted** [comment]
I'm not sure if I feel safe having geo stuff. I'm also not sure how to get keys. So I guess closing.
